=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OddittApiClient::AccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountApi' do
  before do
    # run before each test
    @api_instance = OddittApiClient::AccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountApi' do
    it 'should create an instance of AccountApi' do
      expect(@api_instance).to be_instance_of(OddittApiClient::AccountApi)
    end
  end

  # unit tests for v1_account_api_keys_get
  # List own API keys
  # @param [Hash] opts the optional parameters
  # @return [AuthListAPIKeysResponse]
  describe 'v1_account_api_keys_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_api_keys_key_code_delete
  # Deactivate an API key
  # @param key_code 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_account_api_keys_key_code_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_api_keys_post
  # Create a new API key
  # @param auth_create_api_key_request 
  # @param [Hash] opts the optional parameters
  # @return [AuthCreateAPIKeyResponse]
  describe 'v1_account_api_keys_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_check_endpoint_delete
  # Delete the check endpoint
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_account_check_endpoint_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_check_endpoint_get
  # Get the configured check endpoint
  # Returns the URL, method and bearer token preview for the check endpoint used by flow quoting. The full bearer token is never returned.
  # @param [Hash] opts the optional parameters
  # @return [AuthCheckEndpointResponse]
  describe 'v1_account_check_endpoint_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_check_endpoint_post
  # Set the check endpoint (upsert)
  # Stores or updates the URL, method and bearer token used to quote flows against the client&#39;s own service. A single configuration exists per client.
  # @param auth_set_check_endpoint_request 
  # @param [Hash] opts the optional parameters
  # @return [AuthCheckEndpointResponse]
  describe 'v1_account_check_endpoint_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_config_get
  # Get own client configuration
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_account_config_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_secret_post
  # Create a new client secret
  # @param [Hash] opts the optional parameters
  # @return [AuthCreateSecretResponse]
  describe 'v1_account_secret_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_secrets_get
  # List own client secrets
  # @param [Hash] opts the optional parameters
  # @return [AuthListSecretsResponse]
  describe 'v1_account_secrets_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_secrets_secret_code_delete
  # Delete a client secret
  # @param secret_code 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_account_secrets_secret_code_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_account_usage_get
  # Get own usage stats
  # @param [Hash] opts the optional parameters
  # @option opts [Time] :start_date 
  # @option opts [Time] :end_date 
  # @return [nil]
  describe 'v1_account_usage_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
