=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OddittApiClient::AuthenticationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthenticationApi' do
  before do
    # run before each test
    @api_instance = OddittApiClient::AuthenticationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticationApi' do
    it 'should create an instance of AuthenticationApi' do
      expect(@api_instance).to be_instance_of(OddittApiClient::AuthenticationApi)
    end
  end

  # unit tests for v1_auth_login_post
  # Login with API key
  # @param x_api_key 
  # @param [Hash] opts the optional parameters
  # @return [AuthTokenPair]
  describe 'v1_auth_login_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_auth_refresh_post
  # Refresh tokens
  # @param auth_refresh_request 
  # @param [Hash] opts the optional parameters
  # @return [AuthTokenPair]
  describe 'v1_auth_refresh_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_oauth_login_post
  # OAuth login (client credentials)
  # @param auth_o_auth_login_request 
  # @param [Hash] opts the optional parameters
  # @return [AuthTokenPair]
  describe 'v1_oauth_login_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_oauth_refresh_post
  # OAuth refresh
  # @param auth_refresh_request 
  # @param [Hash] opts the optional parameters
  # @return [AuthTokenPair]
  describe 'v1_oauth_refresh_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
