=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OddittApiClient::HistoricalApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HistoricalApi' do
  before do
    # run before each test
    @api_instance = OddittApiClient::HistoricalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HistoricalApi' do
    it 'should create an instance of HistoricalApi' do
      expect(@api_instance).to be_instance_of(OddittApiClient::HistoricalApi)
    end
  end

  # unit tests for v1_historical_events_get
  # List historical odds events (paginated)
  # Returns a paginated catalog of per-event historical odds files the authenticated client has access to. Each result entry carries pre-baked download URLs for the JSON and CSV payloads; clients GET those URLs directly. Results are scoped to the authenticated client; callers without a client association receive &#x60;403 Forbidden&#x60;. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted. Unknown versions are rejected.
  # @option opts [Integer] :sport_id 
  # @option opts [Integer] :league_id 
  # @option opts [Integer] :team_id Filter to events involving this team as either home or away.
  # @option opts [String] :start_date Inclusive lower bound on the event/affiliation date, ISO format YYYY-MM-DD.
  # @option opts [String] :end_date Inclusive upper bound on the event/affiliation date, ISO format YYYY-MM-DD.
  # @option opts [Integer] :page 
  # @option opts [Integer] :page_size 
  # @return [Object]
  describe 'v1_historical_events_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_historical_odds_event_id_ext_get
  # Download a per-event historical odds file
  # Resolves the requested per-event file for the authenticated client and streams the JSON or CSV payload back. The response body is the raw file content (not the manifest envelope); the API takes care of fetching the bytes from the underlying CDN so callers see a single HTTP call per file.  The &#x60;sha256&#x60; of the bytes-at-rest is exposed as a strong &#x60;ETag&#x60;. Clients can short-circuit with &#x60;If-None-Match&#x60; to receive &#x60;304 Not Modified&#x60;. &#x60;Range&#x60; requests are forwarded upstream and &#x60;206 Partial Content&#x60; responses are relayed unchanged — useful for resuming multi-MB CSV downloads. 
  # @param event_id Canonical event identifier.
  # @param ext File format. &#x60;json&#x60; returns &#x60;application/json&#x60;; &#x60;csv&#x60; returns &#x60;text/csv&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :schema_version Payload schema version. Defaults to &#x60;v1&#x60; when omitted.
  # @return [Object]
  describe 'v1_historical_odds_event_id_ext_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
