=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OddittApiClient::LinksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinksApi' do
  before do
    # run before each test
    @api_instance = OddittApiClient::LinksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinksApi' do
    it 'should create an instance of LinksApi' do
      expect(@api_instance).to be_instance_of(OddittApiClient::LinksApi)
    end
  end

  # unit tests for v1_affiliates_links_bulk_deactivate_post
  # Bulk deactivate links by filter
  # Soft-deletes all links matching a filter (e.g. a state goes offline).
  # @param v1_affiliates_links_bulk_deactivate_post_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_affiliates_links_bulk_deactivate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_affiliates_links_bulk_patch
  # Bulk patch links by filter
  # Applies a patch to all links matching a filter (e.g. rewrite all FanDuel-NJ URLs on a domain change).
  # @param v1_affiliates_links_bulk_patch_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_affiliates_links_bulk_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_affiliates_links_bulk_post
  # Bulk create/upsert links (JSON or CSV)
  # Upserts many links idempotently on the natural key. Accepts a JSON array of row objects or a text/csv body (header row). Per-row errors never fail the batch. Use ?dry_run&#x3D;true to validate without persisting.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :dry_run When true, validates the whole batch and returns the per-row report without persisting. Always synchronous.
  # @option opts [Boolean] :async Force background processing. Batches of 500+ rows are queued automatically regardless of this flag. Queued batches return 202 with a job_id to poll at /v1/affiliates/links/jobs/{job_id}.
  # @return [Object]
  describe 'v1_affiliates_links_bulk_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_affiliates_links_jobs_get
  # List async bulk jobs
  # Recent async bulk jobs for the authenticated client.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_affiliates_links_jobs_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_affiliates_links_jobs_job_id_get
  # Poll an async bulk job
  # Status, counts, and per-row errors for one async bulk job. Poll until status is \&quot;completed\&quot; or \&quot;failed\&quot;. Scoped to the authenticated client.
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_affiliates_links_jobs_job_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_affiliates_links_post
  # Create or upsert a single link
  # Creates a link, or updates the existing one on the natural key (operator + geography + category + campaign + label). Resolves operator, country, and region at write time; unresolvable codes return 422.
  # @param v1_affiliates_links_post_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_affiliates_links_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
