=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OddittApiClient::OddsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OddsApi' do
  before do
    # run before each test
    @api_instance = OddittApiClient::OddsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OddsApi' do
    it 'should create an instance of OddsApi' do
      expect(@api_instance).to be_instance_of(OddittApiClient::OddsApi)
    end
  end

  # unit tests for v1_odds_upcoming_odds_by_event_post
  # Get upcoming odds by event
  # Returns paginated betting market positions for a specific upcoming event, optionally filtered by operator.
  # @param v1_odds_upcoming_odds_by_event_post_request 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'v1_odds_upcoming_odds_by_event_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
