=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OddittApiClient::ReportingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReportingApi' do
  before do
    # run before each test
    @api_instance = OddittApiClient::ReportingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportingApi' do
    it 'should create an instance of ReportingApi' do
      expect(@api_instance).to be_instance_of(OddittApiClient::ReportingApi)
    end
  end

  # unit tests for v1_affiliates_links_clicks_get
  # Impression/click rollups
  # Per-link, per-day impression and click counts for the authenticated client.
  # @param start_date 
  # @param end_date 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :operator_id 
  # @option opts [String] :country_code 
  # @option opts [String] :subnational_region_code 
  # @option opts [String] :offer_campaign 
  # @option opts [String] :offer_label 
  # @return [Object]
  describe 'v1_affiliates_links_clicks_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_affiliates_links_inventory_summary_get
  # Inventory counts
  # Active/inactive link counts grouped by the requested dimension.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :group_by 
  # @return [Object]
  describe 'v1_affiliates_links_inventory_summary_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
