=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OddittApiClient::TelemetryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TelemetryApi' do
  before do
    # run before each test
    @api_instance = OddittApiClient::TelemetryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TelemetryApi' do
    it 'should create an instance of TelemetryApi' do
      expect(@api_instance).to be_instance_of(OddittApiClient::TelemetryApi)
    end
  end

  # unit tests for v1_affiliates_events_post
  # Log an impression or click
  # Fire-and-forget telemetry. Records one impression (card render) or click (deeplink tap). Returns 202 on accept; never blocks the widget&#39;s click-out.
  # @param v1_affiliates_events_post_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_affiliates_events_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
