=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OddittApiClient::TrendsErrorResponseError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OddittApiClient::TrendsErrorResponseError do
  #let(:instance) { OddittApiClient::TrendsErrorResponseError.new }

  describe 'test an instance of TrendsErrorResponseError' do
    it 'should create an instance of TrendsErrorResponseError' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OddittApiClient::TrendsErrorResponseError)
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["BAD_REQUEST", "VALIDATION_ERROR", "AMBIGUOUS_LOOKUP", "UNAUTHORIZED", "FORBIDDEN", "NOT_FOUND", "RATE_LIMIT_EXCEEDED", "INTERNAL_ERROR"])
      # validator.allowable_values.each do |value|
      #   expect { instance.code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
