=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OddittApiClient::TrendsQuoteFlowItem
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OddittApiClient::TrendsQuoteFlowItem do
  #let(:instance) { OddittApiClient::TrendsQuoteFlowItem.new }

  describe 'test an instance of TrendsQuoteFlowItem' do
    it 'should create an instance of TrendsQuoteFlowItem' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OddittApiClient::TrendsQuoteFlowItem)
    end
  end

  describe 'test attribute "country"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "event_betting_market_position_ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "flow_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "flow_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["fact_flow", "fun_flow", "fact_flow_parlay", "fun_flow_parlay", "plain_flow_parlay"])
      # validator.allowable_values.each do |value|
      #   expect { instance.flow_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "region"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
