=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OddittApiClient::TrendsWidgetEventRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OddittApiClient::TrendsWidgetEventRequest do
  #let(:instance) { OddittApiClient::TrendsWidgetEventRequest.new }

  describe 'test an instance of TrendsWidgetEventRequest' do
    it 'should create an instance of TrendsWidgetEventRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OddittApiClient::TrendsWidgetEventRequest)
    end
  end

  describe 'test attribute "event_body"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "event_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["impression", "click", "dwell", "cart_open", "cart_offers_shown", "cart_dismiss", "card_click", "graph_expand", "graph_metric_change", "filter_change", "widget-impression", "widget-viewed", "betslip-clicked", "betslip-shared", "flow-clicked", "flow-shared"])
      # validator.allowable_values.each do |value|
      #   expect { instance.event_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "mode"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["operator", "affiliate", "clean"])
      # validator.allowable_values.each do |value|
      #   expect { instance.mode = value }.not_to raise_error
      # end
    end
  end

end
