=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OddittApiClient::V1TrendsByBettingMarketPositionPostRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OddittApiClient::V1TrendsByBettingMarketPositionPostRequest do
  #let(:instance) { OddittApiClient::V1TrendsByBettingMarketPositionPostRequest.new }

  describe 'test an instance of V1TrendsByBettingMarketPositionPostRequest' do
    it 'should create an instance of V1TrendsByBettingMarketPositionPostRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OddittApiClient::V1TrendsByBettingMarketPositionPostRequest)
    end
  end

  describe 'test attribute "event_betting_market_position_ids"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "odds_format"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["american", "decimal", "fractional", "multiplier", "percent"])
      # validator.allowable_values.each do |value|
      #   expect { instance.odds_format = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "product_mode"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["sportsbook", "dfs", "prediction_market"])
      # validator.allowable_values.each do |value|
      #   expect { instance.product_mode = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "use_cartoon_images"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
