=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'cgi'

module OddittApiClient
  class AccountApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List own API keys
    # @param [Hash] opts the optional parameters
    # @return [AuthListAPIKeysResponse]
    def v1_account_api_keys_get(opts = {})
      data, _status_code, _headers = v1_account_api_keys_get_with_http_info(opts)
      data
    end

    # List own API keys
    # @param [Hash] opts the optional parameters
    # @return [Array<(AuthListAPIKeysResponse, Integer, Hash)>] AuthListAPIKeysResponse data, response status code and response headers
    def v1_account_api_keys_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_api_keys_get ...'
      end
      # resource path
      local_var_path = '/v1/account/api-keys'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AuthListAPIKeysResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_api_keys_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_api_keys_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Deactivate an API key
    # @param key_code [String] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def v1_account_api_keys_key_code_delete(key_code, opts = {})
      v1_account_api_keys_key_code_delete_with_http_info(key_code, opts)
      nil
    end

    # Deactivate an API key
    # @param key_code [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def v1_account_api_keys_key_code_delete_with_http_info(key_code, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_api_keys_key_code_delete ...'
      end
      # verify the required parameter 'key_code' is set
      if @api_client.config.client_side_validation && key_code.nil?
        fail ArgumentError, "Missing the required parameter 'key_code' when calling AccountApi.v1_account_api_keys_key_code_delete"
      end
      # resource path
      local_var_path = '/v1/account/api-keys/{key_code}'.sub('{key_code}', CGI.escape(key_code.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_api_keys_key_code_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_api_keys_key_code_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create a new API key
    # @param auth_create_api_key_request [AuthCreateAPIKeyRequest] 
    # @param [Hash] opts the optional parameters
    # @return [AuthCreateAPIKeyResponse]
    def v1_account_api_keys_post(auth_create_api_key_request, opts = {})
      data, _status_code, _headers = v1_account_api_keys_post_with_http_info(auth_create_api_key_request, opts)
      data
    end

    # Create a new API key
    # @param auth_create_api_key_request [AuthCreateAPIKeyRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(AuthCreateAPIKeyResponse, Integer, Hash)>] AuthCreateAPIKeyResponse data, response status code and response headers
    def v1_account_api_keys_post_with_http_info(auth_create_api_key_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_api_keys_post ...'
      end
      # verify the required parameter 'auth_create_api_key_request' is set
      if @api_client.config.client_side_validation && auth_create_api_key_request.nil?
        fail ArgumentError, "Missing the required parameter 'auth_create_api_key_request' when calling AccountApi.v1_account_api_keys_post"
      end
      # resource path
      local_var_path = '/v1/account/api-keys'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(auth_create_api_key_request)

      # return_type
      return_type = opts[:debug_return_type] || 'AuthCreateAPIKeyResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_api_keys_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_api_keys_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete the check endpoint
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def v1_account_check_endpoint_delete(opts = {})
      v1_account_check_endpoint_delete_with_http_info(opts)
      nil
    end

    # Delete the check endpoint
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def v1_account_check_endpoint_delete_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_check_endpoint_delete ...'
      end
      # resource path
      local_var_path = '/v1/account/check-endpoint'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_check_endpoint_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_check_endpoint_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get the configured check endpoint
    # Returns the URL, method and bearer token preview for the check endpoint used by flow quoting. The full bearer token is never returned.
    # @param [Hash] opts the optional parameters
    # @return [AuthCheckEndpointResponse]
    def v1_account_check_endpoint_get(opts = {})
      data, _status_code, _headers = v1_account_check_endpoint_get_with_http_info(opts)
      data
    end

    # Get the configured check endpoint
    # Returns the URL, method and bearer token preview for the check endpoint used by flow quoting. The full bearer token is never returned.
    # @param [Hash] opts the optional parameters
    # @return [Array<(AuthCheckEndpointResponse, Integer, Hash)>] AuthCheckEndpointResponse data, response status code and response headers
    def v1_account_check_endpoint_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_check_endpoint_get ...'
      end
      # resource path
      local_var_path = '/v1/account/check-endpoint'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AuthCheckEndpointResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_check_endpoint_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_check_endpoint_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Set the check endpoint (upsert)
    # Stores or updates the URL, method and bearer token used to quote flows against the client's own service. A single configuration exists per client.
    # @param auth_set_check_endpoint_request [AuthSetCheckEndpointRequest] 
    # @param [Hash] opts the optional parameters
    # @return [AuthCheckEndpointResponse]
    def v1_account_check_endpoint_post(auth_set_check_endpoint_request, opts = {})
      data, _status_code, _headers = v1_account_check_endpoint_post_with_http_info(auth_set_check_endpoint_request, opts)
      data
    end

    # Set the check endpoint (upsert)
    # Stores or updates the URL, method and bearer token used to quote flows against the client&#39;s own service. A single configuration exists per client.
    # @param auth_set_check_endpoint_request [AuthSetCheckEndpointRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(AuthCheckEndpointResponse, Integer, Hash)>] AuthCheckEndpointResponse data, response status code and response headers
    def v1_account_check_endpoint_post_with_http_info(auth_set_check_endpoint_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_check_endpoint_post ...'
      end
      # verify the required parameter 'auth_set_check_endpoint_request' is set
      if @api_client.config.client_side_validation && auth_set_check_endpoint_request.nil?
        fail ArgumentError, "Missing the required parameter 'auth_set_check_endpoint_request' when calling AccountApi.v1_account_check_endpoint_post"
      end
      # resource path
      local_var_path = '/v1/account/check-endpoint'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(auth_set_check_endpoint_request)

      # return_type
      return_type = opts[:debug_return_type] || 'AuthCheckEndpointResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_check_endpoint_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_check_endpoint_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get own client configuration
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def v1_account_config_get(opts = {})
      v1_account_config_get_with_http_info(opts)
      nil
    end

    # Get own client configuration
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def v1_account_config_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_config_get ...'
      end
      # resource path
      local_var_path = '/v1/account/config'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_config_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_config_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create a new client secret
    # @param [Hash] opts the optional parameters
    # @return [AuthCreateSecretResponse]
    def v1_account_secret_post(opts = {})
      data, _status_code, _headers = v1_account_secret_post_with_http_info(opts)
      data
    end

    # Create a new client secret
    # @param [Hash] opts the optional parameters
    # @return [Array<(AuthCreateSecretResponse, Integer, Hash)>] AuthCreateSecretResponse data, response status code and response headers
    def v1_account_secret_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_secret_post ...'
      end
      # resource path
      local_var_path = '/v1/account/secret'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AuthCreateSecretResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_secret_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_secret_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List own client secrets
    # @param [Hash] opts the optional parameters
    # @return [AuthListSecretsResponse]
    def v1_account_secrets_get(opts = {})
      data, _status_code, _headers = v1_account_secrets_get_with_http_info(opts)
      data
    end

    # List own client secrets
    # @param [Hash] opts the optional parameters
    # @return [Array<(AuthListSecretsResponse, Integer, Hash)>] AuthListSecretsResponse data, response status code and response headers
    def v1_account_secrets_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_secrets_get ...'
      end
      # resource path
      local_var_path = '/v1/account/secrets'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'AuthListSecretsResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_secrets_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_secrets_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete a client secret
    # @param secret_code [String] 
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def v1_account_secrets_secret_code_delete(secret_code, opts = {})
      v1_account_secrets_secret_code_delete_with_http_info(secret_code, opts)
      nil
    end

    # Delete a client secret
    # @param secret_code [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def v1_account_secrets_secret_code_delete_with_http_info(secret_code, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_secrets_secret_code_delete ...'
      end
      # verify the required parameter 'secret_code' is set
      if @api_client.config.client_side_validation && secret_code.nil?
        fail ArgumentError, "Missing the required parameter 'secret_code' when calling AccountApi.v1_account_secrets_secret_code_delete"
      end
      # resource path
      local_var_path = '/v1/account/secrets/{secret_code}'.sub('{secret_code}', CGI.escape(secret_code.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_secrets_secret_code_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_secrets_secret_code_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get own usage stats
    # @param [Hash] opts the optional parameters
    # @option opts [Time] :start_date 
    # @option opts [Time] :end_date 
    # @return [nil]
    def v1_account_usage_get(opts = {})
      v1_account_usage_get_with_http_info(opts)
      nil
    end

    # Get own usage stats
    # @param [Hash] opts the optional parameters
    # @option opts [Time] :start_date 
    # @option opts [Time] :end_date 
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def v1_account_usage_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AccountApi.v1_account_usage_get ...'
      end
      # resource path
      local_var_path = '/v1/account/usage'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'start_date'] = opts[:'start_date'] if !opts[:'start_date'].nil?
      query_params[:'end_date'] = opts[:'end_date'] if !opts[:'end_date'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"AccountApi.v1_account_usage_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AccountApi#v1_account_usage_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
