=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'cgi'

module OddittApiClient
  class OffersApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Paginated client deals
    # Paginated client deals (carousel/featured/list), optionally enriched with operator reviews. Scoped to the authenticated client.
    # @param [Hash] opts the optional parameters
    # @option opts [V1AffiliatesDealsPostRequest] :v1_affiliates_deals_post_request 
    # @return [Object]
    def v1_affiliates_deals_post(opts = {})
      data, _status_code, _headers = v1_affiliates_deals_post_with_http_info(opts)
      data
    end

    # Paginated client deals
    # Paginated client deals (carousel/featured/list), optionally enriched with operator reviews. Scoped to the authenticated client.
    # @param [Hash] opts the optional parameters
    # @option opts [V1AffiliatesDealsPostRequest] :v1_affiliates_deals_post_request 
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def v1_affiliates_deals_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OffersApi.v1_affiliates_deals_post ...'
      end
      # resource path
      local_var_path = '/v1/affiliates/deals'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'v1_affiliates_deals_post_request'])

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuth', 'BearerAuth']

      new_options = opts.merge(
        :operation => :"OffersApi.v1_affiliates_deals_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OffersApi#v1_affiliates_deals_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Client offer cards for a geography
    # Returns the calling client's best operator offer card per operator for a geography. The core offers read the widget cart renders.
    # @param [Hash] opts the optional parameters
    # @option opts [V1AffiliatesOffersPostRequest] :v1_affiliates_offers_post_request 
    # @return [Object]
    def v1_affiliates_offers_post(opts = {})
      data, _status_code, _headers = v1_affiliates_offers_post_with_http_info(opts)
      data
    end

    # Client offer cards for a geography
    # Returns the calling client&#39;s best operator offer card per operator for a geography. The core offers read the widget cart renders.
    # @param [Hash] opts the optional parameters
    # @option opts [V1AffiliatesOffersPostRequest] :v1_affiliates_offers_post_request 
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def v1_affiliates_offers_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OffersApi.v1_affiliates_offers_post ...'
      end
      # resource path
      local_var_path = '/v1/affiliates/offers'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(opts[:'v1_affiliates_offers_post_request'])

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['ApiKeyAuth', 'BearerAuth']

      new_options = opts.merge(
        :operation => :"OffersApi.v1_affiliates_offers_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OffersApi#v1_affiliates_offers_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
