=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

# Common files
require 'odditt_api_client/api_client'
require 'odditt_api_client/api_error'
require 'odditt_api_client/api_model_base'
require 'odditt_api_client/version'
require 'odditt_api_client/configuration'

# Models
require 'odditt_api_client/models/affiliate_error_response'
require 'odditt_api_client/models/affiliate_error_response_error'
require 'odditt_api_client/models/auth_check_endpoint_response'
require 'odditt_api_client/models/auth_check_endpoint_response_data'
require 'odditt_api_client/models/auth_create_api_key_request'
require 'odditt_api_client/models/auth_create_api_key_response'
require 'odditt_api_client/models/auth_create_secret_response'
require 'odditt_api_client/models/auth_error_response'
require 'odditt_api_client/models/auth_list_api_keys_response'
require 'odditt_api_client/models/auth_list_api_keys_response_api_keys_inner'
require 'odditt_api_client/models/auth_list_secrets_response'
require 'odditt_api_client/models/auth_list_secrets_response_secrets_inner'
require 'odditt_api_client/models/auth_o_auth_login_request'
require 'odditt_api_client/models/auth_refresh_request'
require 'odditt_api_client/models/auth_set_check_endpoint_request'
require 'odditt_api_client/models/auth_token_pair'
require 'odditt_api_client/models/trends_error_response'
require 'odditt_api_client/models/trends_error_response_error'
require 'odditt_api_client/models/trends_paginated_response'
require 'odditt_api_client/models/trends_quote_flow_item'
require 'odditt_api_client/models/trends_quote_item_result'
require 'odditt_api_client/models/trends_quote_sandbox_request'
require 'odditt_api_client/models/trends_quote_sandbox_response'
require 'odditt_api_client/models/trends_widget_event_request'
require 'odditt_api_client/models/trends_widget_event_response'
require 'odditt_api_client/models/v1_account_api_keys_key_code_delete409_response'
require 'odditt_api_client/models/v1_affiliates_deals_post_request'
require 'odditt_api_client/models/v1_affiliates_event_position_post_request'
require 'odditt_api_client/models/v1_affiliates_events_post_request'
require 'odditt_api_client/models/v1_affiliates_links_bulk_deactivate_post_request'
require 'odditt_api_client/models/v1_affiliates_links_bulk_patch_request'
require 'odditt_api_client/models/v1_affiliates_links_bulk_post202_response'
require 'odditt_api_client/models/v1_affiliates_links_post_request'
require 'odditt_api_client/models/v1_affiliates_offers_post_request'
require 'odditt_api_client/models/v1_affiliates_parlay_post_request'
require 'odditt_api_client/models/v1_events_upcoming_events_post_request'
require 'odditt_api_client/models/v1_odds_upcoming_odds_by_event_post_request'
require 'odditt_api_client/models/v1_references_tag_dimensions_get200_response'
require 'odditt_api_client/models/v1_references_tag_types_tag_type_id_children_get200_response'
require 'odditt_api_client/models/v1_trends_by_betting_market_position_post_request'
require 'odditt_api_client/models/v1_trends_flows_by_id_post_request'
require 'odditt_api_client/models/v1_trends_flows_post_request'

# APIs
require 'odditt_api_client/api/account_api'
require 'odditt_api_client/api/affiliates_api'
require 'odditt_api_client/api/authentication_api'
require 'odditt_api_client/api/events_api'
require 'odditt_api_client/api/historical_api'
require 'odditt_api_client/api/links_api'
require 'odditt_api_client/api/lookups_api'
require 'odditt_api_client/api/odds_api'
require 'odditt_api_client/api/offers_api'
require 'odditt_api_client/api/references_api'
require 'odditt_api_client/api/reporting_api'
require 'odditt_api_client/api/telemetry_api'
require 'odditt_api_client/api/trends_api'

module OddittApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OddittApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
