=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  # Single hydrated pricing payload — the exact shape /v1/trends/flows/quote sends in each outbound call. Wire this endpoint into /v1/account/check-endpoint to round-trip the widget call entirely on platform infrastructure (no real operator needed).
  class TrendsQuoteSandboxRequest < ApiModelBase
    attr_accessor :country

    # Hydrated leg array, identical to what the quote endpoint POSTs to a real operator. Pass it through unchanged.
    attr_accessor :event_betting_market_position_maps

    attr_accessor :flow_id

    attr_accessor :flow_type

    attr_accessor :region

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'country' => :'country',
        :'event_betting_market_position_maps' => :'event_betting_market_position_maps',
        :'flow_id' => :'flow_id',
        :'flow_type' => :'flow_type',
        :'region' => :'region'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'country' => :'String',
        :'event_betting_market_position_maps' => :'Array<Object>',
        :'flow_id' => :'Integer',
        :'flow_type' => :'String',
        :'region' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::TrendsQuoteSandboxRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::TrendsQuoteSandboxRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      else
        self.country = nil
      end

      if attributes.key?(:'event_betting_market_position_maps')
        if (value = attributes[:'event_betting_market_position_maps']).is_a?(Array)
          self.event_betting_market_position_maps = value
        end
      else
        self.event_betting_market_position_maps = nil
      end

      if attributes.key?(:'flow_id')
        self.flow_id = attributes[:'flow_id']
      else
        self.flow_id = nil
      end

      if attributes.key?(:'flow_type')
        self.flow_type = attributes[:'flow_type']
      else
        self.flow_type = nil
      end

      if attributes.key?(:'region')
        self.region = attributes[:'region']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @country.nil?
        invalid_properties.push('invalid value for "country", country cannot be nil.')
      end

      if @country.to_s.length > 2
        invalid_properties.push('invalid value for "country", the character length must be smaller than or equal to 2.')
      end

      if @country.to_s.length < 2
        invalid_properties.push('invalid value for "country", the character length must be greater than or equal to 2.')
      end

      if @event_betting_market_position_maps.nil?
        invalid_properties.push('invalid value for "event_betting_market_position_maps", event_betting_market_position_maps cannot be nil.')
      end

      if @flow_id.nil?
        invalid_properties.push('invalid value for "flow_id", flow_id cannot be nil.')
      end

      if @flow_type.nil?
        invalid_properties.push('invalid value for "flow_type", flow_type cannot be nil.')
      end

      if !@region.nil? && @region.to_s.length > 3
        invalid_properties.push('invalid value for "region", the character length must be smaller than or equal to 3.')
      end

      if !@region.nil? && @region.to_s.length < 2
        invalid_properties.push('invalid value for "region", the character length must be greater than or equal to 2.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @country.nil?
      return false if @country.to_s.length > 2
      return false if @country.to_s.length < 2
      return false if @event_betting_market_position_maps.nil?
      return false if @flow_id.nil?
      return false if @flow_type.nil?
      flow_type_validator = EnumAttributeValidator.new('String', ["fact_flow", "fun_flow", "fact_flow_parlay", "fun_flow_parlay", "plain_flow_parlay"])
      return false unless flow_type_validator.valid?(@flow_type)
      return false if !@region.nil? && @region.to_s.length > 3
      return false if !@region.nil? && @region.to_s.length < 2
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] country Value to be assigned
    def country=(country)
      if country.nil?
        fail ArgumentError, 'country cannot be nil'
      end

      if country.to_s.length > 2
        fail ArgumentError, 'invalid value for "country", the character length must be smaller than or equal to 2.'
      end

      if country.to_s.length < 2
        fail ArgumentError, 'invalid value for "country", the character length must be greater than or equal to 2.'
      end

      @country = country
    end

    # Custom attribute writer method with validation
    # @param [Object] event_betting_market_position_maps Value to be assigned
    def event_betting_market_position_maps=(event_betting_market_position_maps)
      if event_betting_market_position_maps.nil?
        fail ArgumentError, 'event_betting_market_position_maps cannot be nil'
      end

      @event_betting_market_position_maps = event_betting_market_position_maps
    end

    # Custom attribute writer method with validation
    # @param [Object] flow_id Value to be assigned
    def flow_id=(flow_id)
      if flow_id.nil?
        fail ArgumentError, 'flow_id cannot be nil'
      end

      @flow_id = flow_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] flow_type Object to be assigned
    def flow_type=(flow_type)
      validator = EnumAttributeValidator.new('String', ["fact_flow", "fun_flow", "fact_flow_parlay", "fun_flow_parlay", "plain_flow_parlay"])
      unless validator.valid?(flow_type)
        fail ArgumentError, "invalid value for \"flow_type\", must be one of #{validator.allowable_values}."
      end
      @flow_type = flow_type
    end

    # Custom attribute writer method with validation
    # @param [Object] region Value to be assigned
    def region=(region)
      if region.nil?
        fail ArgumentError, 'region cannot be nil'
      end

      if region.to_s.length > 3
        fail ArgumentError, 'invalid value for "region", the character length must be smaller than or equal to 3.'
      end

      if region.to_s.length < 2
        fail ArgumentError, 'invalid value for "region", the character length must be greater than or equal to 2.'
      end

      @region = region
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          country == o.country &&
          event_betting_market_position_maps == o.event_betting_market_position_maps &&
          flow_id == o.flow_id &&
          flow_type == o.flow_type &&
          region == o.region
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [country, event_betting_market_position_maps, flow_id, flow_type, region].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
