=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  # Mock pricing response. Shape differs between single (1-leg) and parlay (2+ legs); parlay responses additionally carry top-level combined odds and is_combinable / parlay_failure_reason.
  class TrendsQuoteSandboxResponse < ApiModelBase
    # Parlay only. Null when uncombinable.
    attr_accessor :american_odds_value

    # Synthetic bet-slip identifier (prefix 'FD-MOCK-'). Null when the result is invalid or the parlay is uncombinable.
    attr_accessor :button_payload

    attr_accessor :decimal_odds_value

    attr_accessor :event_betting_market_position_maps

    attr_accessor :flow_id

    attr_accessor :flow_type

    attr_accessor :fractional_odds_value

    # Parlay only. False if any leg failed or the parlay-level uncombinable roll fired.
    attr_accessor :is_combinable

    attr_accessor :odds_implied_probability

    attr_accessor :parlay_failure_reason

    attr_accessor :payout_multiplier

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'american_odds_value' => :'american_odds_value',
        :'button_payload' => :'button_payload',
        :'decimal_odds_value' => :'decimal_odds_value',
        :'event_betting_market_position_maps' => :'event_betting_market_position_maps',
        :'flow_id' => :'flow_id',
        :'flow_type' => :'flow_type',
        :'fractional_odds_value' => :'fractional_odds_value',
        :'is_combinable' => :'is_combinable',
        :'odds_implied_probability' => :'odds_implied_probability',
        :'parlay_failure_reason' => :'parlay_failure_reason',
        :'payout_multiplier' => :'payout_multiplier'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'american_odds_value' => :'String',
        :'button_payload' => :'String',
        :'decimal_odds_value' => :'Float',
        :'event_betting_market_position_maps' => :'Array<Object>',
        :'flow_id' => :'Integer',
        :'flow_type' => :'String',
        :'fractional_odds_value' => :'String',
        :'is_combinable' => :'Boolean',
        :'odds_implied_probability' => :'Float',
        :'parlay_failure_reason' => :'String',
        :'payout_multiplier' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'american_odds_value',
        :'button_payload',
        :'decimal_odds_value',
        :'fractional_odds_value',
        :'odds_implied_probability',
        :'parlay_failure_reason',
        :'payout_multiplier'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::TrendsQuoteSandboxResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::TrendsQuoteSandboxResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'american_odds_value')
        self.american_odds_value = attributes[:'american_odds_value']
      end

      if attributes.key?(:'button_payload')
        self.button_payload = attributes[:'button_payload']
      end

      if attributes.key?(:'decimal_odds_value')
        self.decimal_odds_value = attributes[:'decimal_odds_value']
      end

      if attributes.key?(:'event_betting_market_position_maps')
        if (value = attributes[:'event_betting_market_position_maps']).is_a?(Array)
          self.event_betting_market_position_maps = value
        end
      else
        self.event_betting_market_position_maps = nil
      end

      if attributes.key?(:'flow_id')
        self.flow_id = attributes[:'flow_id']
      else
        self.flow_id = nil
      end

      if attributes.key?(:'flow_type')
        self.flow_type = attributes[:'flow_type']
      else
        self.flow_type = nil
      end

      if attributes.key?(:'fractional_odds_value')
        self.fractional_odds_value = attributes[:'fractional_odds_value']
      end

      if attributes.key?(:'is_combinable')
        self.is_combinable = attributes[:'is_combinable']
      end

      if attributes.key?(:'odds_implied_probability')
        self.odds_implied_probability = attributes[:'odds_implied_probability']
      end

      if attributes.key?(:'parlay_failure_reason')
        self.parlay_failure_reason = attributes[:'parlay_failure_reason']
      end

      if attributes.key?(:'payout_multiplier')
        self.payout_multiplier = attributes[:'payout_multiplier']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @event_betting_market_position_maps.nil?
        invalid_properties.push('invalid value for "event_betting_market_position_maps", event_betting_market_position_maps cannot be nil.')
      end

      if @flow_id.nil?
        invalid_properties.push('invalid value for "flow_id", flow_id cannot be nil.')
      end

      if @flow_type.nil?
        invalid_properties.push('invalid value for "flow_type", flow_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @event_betting_market_position_maps.nil?
      return false if @flow_id.nil?
      return false if @flow_type.nil?
      parlay_failure_reason_validator = EnumAttributeValidator.new('String', ["one or more legs failed", "selections are not combinable"])
      return false unless parlay_failure_reason_validator.valid?(@parlay_failure_reason)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] event_betting_market_position_maps Value to be assigned
    def event_betting_market_position_maps=(event_betting_market_position_maps)
      if event_betting_market_position_maps.nil?
        fail ArgumentError, 'event_betting_market_position_maps cannot be nil'
      end

      @event_betting_market_position_maps = event_betting_market_position_maps
    end

    # Custom attribute writer method with validation
    # @param [Object] flow_id Value to be assigned
    def flow_id=(flow_id)
      if flow_id.nil?
        fail ArgumentError, 'flow_id cannot be nil'
      end

      @flow_id = flow_id
    end

    # Custom attribute writer method with validation
    # @param [Object] flow_type Value to be assigned
    def flow_type=(flow_type)
      if flow_type.nil?
        fail ArgumentError, 'flow_type cannot be nil'
      end

      @flow_type = flow_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] parlay_failure_reason Object to be assigned
    def parlay_failure_reason=(parlay_failure_reason)
      validator = EnumAttributeValidator.new('String', ["one or more legs failed", "selections are not combinable"])
      unless validator.valid?(parlay_failure_reason)
        fail ArgumentError, "invalid value for \"parlay_failure_reason\", must be one of #{validator.allowable_values}."
      end
      @parlay_failure_reason = parlay_failure_reason
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          american_odds_value == o.american_odds_value &&
          button_payload == o.button_payload &&
          decimal_odds_value == o.decimal_odds_value &&
          event_betting_market_position_maps == o.event_betting_market_position_maps &&
          flow_id == o.flow_id &&
          flow_type == o.flow_type &&
          fractional_odds_value == o.fractional_odds_value &&
          is_combinable == o.is_combinable &&
          odds_implied_probability == o.odds_implied_probability &&
          parlay_failure_reason == o.parlay_failure_reason &&
          payout_multiplier == o.payout_multiplier
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [american_odds_value, button_payload, decimal_odds_value, event_betting_market_position_maps, flow_id, flow_type, fractional_odds_value, is_combinable, odds_implied_probability, parlay_failure_reason, payout_multiplier].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
