=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  class V1AffiliatesEventPositionPostRequest < ApiModelBase
    # ISO 3166-1 alpha-2 country code.
    attr_accessor :country_code

    # The event betting market position to build the cart for.
    attr_accessor :event_betting_market_position_id

    # When true, offer metadata is returned without the deep-link URLs.
    attr_accessor :hide_offers_links

    # Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
    attr_accessor :odds_format

    # Optional campaign filter. Renders only offers tagged with this campaign.
    attr_accessor :offer_campaign

    # Optional list of operator IDs to gate which operators appear in the cart.
    attr_accessor :operator_ids

    # Optional operator external keys (e.g. 'draftkings'). Resolved IDs are merged with operator_ids.
    attr_accessor :operator_keys

    # Display mode. dfs rewrites leg stat lines to MORE/LESS.
    attr_accessor :product_mode

    # ISO 3166-2 subnational region code (used for offer/deeplink resolution).
    attr_accessor :subnational_region_code

    # When true, swaps default operator/jersey imagery for cartoon variants.
    attr_accessor :use_cartoon_images

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'country_code' => :'country_code',
        :'event_betting_market_position_id' => :'event_betting_market_position_id',
        :'hide_offers_links' => :'hide_offers_links',
        :'odds_format' => :'odds_format',
        :'offer_campaign' => :'offer_campaign',
        :'operator_ids' => :'operator_ids',
        :'operator_keys' => :'operator_keys',
        :'product_mode' => :'product_mode',
        :'subnational_region_code' => :'subnational_region_code',
        :'use_cartoon_images' => :'use_cartoon_images'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'country_code' => :'String',
        :'event_betting_market_position_id' => :'Integer',
        :'hide_offers_links' => :'Boolean',
        :'odds_format' => :'String',
        :'offer_campaign' => :'String',
        :'operator_ids' => :'Array<Integer>',
        :'operator_keys' => :'Array<String>',
        :'product_mode' => :'String',
        :'subnational_region_code' => :'String',
        :'use_cartoon_images' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::V1AffiliatesEventPositionPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::V1AffiliatesEventPositionPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      else
        self.country_code = 'US'
      end

      if attributes.key?(:'event_betting_market_position_id')
        self.event_betting_market_position_id = attributes[:'event_betting_market_position_id']
      else
        self.event_betting_market_position_id = nil
      end

      if attributes.key?(:'hide_offers_links')
        self.hide_offers_links = attributes[:'hide_offers_links']
      end

      if attributes.key?(:'odds_format')
        self.odds_format = attributes[:'odds_format']
      end

      if attributes.key?(:'offer_campaign')
        self.offer_campaign = attributes[:'offer_campaign']
      end

      if attributes.key?(:'operator_ids')
        if (value = attributes[:'operator_ids']).is_a?(Array)
          self.operator_ids = value
        end
      end

      if attributes.key?(:'operator_keys')
        if (value = attributes[:'operator_keys']).is_a?(Array)
          self.operator_keys = value
        end
      end

      if attributes.key?(:'product_mode')
        self.product_mode = attributes[:'product_mode']
      end

      if attributes.key?(:'subnational_region_code')
        self.subnational_region_code = attributes[:'subnational_region_code']
      end

      if attributes.key?(:'use_cartoon_images')
        self.use_cartoon_images = attributes[:'use_cartoon_images']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@country_code.nil? && @country_code.to_s.length > 2
        invalid_properties.push('invalid value for "country_code", the character length must be smaller than or equal to 2.')
      end

      if !@country_code.nil? && @country_code.to_s.length < 2
        invalid_properties.push('invalid value for "country_code", the character length must be greater than or equal to 2.')
      end

      if @event_betting_market_position_id.nil?
        invalid_properties.push('invalid value for "event_betting_market_position_id", event_betting_market_position_id cannot be nil.')
      end

      if @event_betting_market_position_id < 1
        invalid_properties.push('invalid value for "event_betting_market_position_id", must be greater than or equal to 1.')
      end

      if !@subnational_region_code.nil? && @subnational_region_code.to_s.length > 10
        invalid_properties.push('invalid value for "subnational_region_code", the character length must be smaller than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@country_code.nil? && @country_code.to_s.length > 2
      return false if !@country_code.nil? && @country_code.to_s.length < 2
      return false if @event_betting_market_position_id.nil?
      return false if @event_betting_market_position_id < 1
      odds_format_validator = EnumAttributeValidator.new('String', ["american", "decimal", "fractional", "multiplier", "percent"])
      return false unless odds_format_validator.valid?(@odds_format)
      product_mode_validator = EnumAttributeValidator.new('String', ["sportsbook", "dfs", "prediction_market"])
      return false unless product_mode_validator.valid?(@product_mode)
      return false if !@subnational_region_code.nil? && @subnational_region_code.to_s.length > 10
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] country_code Value to be assigned
    def country_code=(country_code)
      if country_code.nil?
        fail ArgumentError, 'country_code cannot be nil'
      end

      if country_code.to_s.length > 2
        fail ArgumentError, 'invalid value for "country_code", the character length must be smaller than or equal to 2.'
      end

      if country_code.to_s.length < 2
        fail ArgumentError, 'invalid value for "country_code", the character length must be greater than or equal to 2.'
      end

      @country_code = country_code
    end

    # Custom attribute writer method with validation
    # @param [Object] event_betting_market_position_id Value to be assigned
    def event_betting_market_position_id=(event_betting_market_position_id)
      if event_betting_market_position_id.nil?
        fail ArgumentError, 'event_betting_market_position_id cannot be nil'
      end

      if event_betting_market_position_id < 1
        fail ArgumentError, 'invalid value for "event_betting_market_position_id", must be greater than or equal to 1.'
      end

      @event_betting_market_position_id = event_betting_market_position_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] odds_format Object to be assigned
    def odds_format=(odds_format)
      validator = EnumAttributeValidator.new('String', ["american", "decimal", "fractional", "multiplier", "percent"])
      unless validator.valid?(odds_format)
        fail ArgumentError, "invalid value for \"odds_format\", must be one of #{validator.allowable_values}."
      end
      @odds_format = odds_format
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] product_mode Object to be assigned
    def product_mode=(product_mode)
      validator = EnumAttributeValidator.new('String', ["sportsbook", "dfs", "prediction_market"])
      unless validator.valid?(product_mode)
        fail ArgumentError, "invalid value for \"product_mode\", must be one of #{validator.allowable_values}."
      end
      @product_mode = product_mode
    end

    # Custom attribute writer method with validation
    # @param [Object] subnational_region_code Value to be assigned
    def subnational_region_code=(subnational_region_code)
      if subnational_region_code.nil?
        fail ArgumentError, 'subnational_region_code cannot be nil'
      end

      if subnational_region_code.to_s.length > 10
        fail ArgumentError, 'invalid value for "subnational_region_code", the character length must be smaller than or equal to 10.'
      end

      @subnational_region_code = subnational_region_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          country_code == o.country_code &&
          event_betting_market_position_id == o.event_betting_market_position_id &&
          hide_offers_links == o.hide_offers_links &&
          odds_format == o.odds_format &&
          offer_campaign == o.offer_campaign &&
          operator_ids == o.operator_ids &&
          operator_keys == o.operator_keys &&
          product_mode == o.product_mode &&
          subnational_region_code == o.subnational_region_code &&
          use_cartoon_images == o.use_cartoon_images
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [country_code, event_betting_market_position_id, hide_offers_links, odds_format, offer_campaign, operator_ids, operator_keys, product_mode, subnational_region_code, use_cartoon_images].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
