=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  class V1AffiliatesLinksPostRequest < ApiModelBase
    attr_accessor :android_deep_link_url

    attr_accessor :country_code

    attr_accessor :ios_deep_link_url

    attr_accessor :is_active

    attr_accessor :offer_call_to_action

    attr_accessor :offer_campaign

    attr_accessor :offer_category_id

    attr_accessor :offer_display_bullets

    attr_accessor :offer_display_small_print

    attr_accessor :offer_ev_usd

    attr_accessor :offer_label

    attr_accessor :offer_priority

    attr_accessor :offer_tagline

    # One of operator_id or operator_name is required.
    attr_accessor :operator_id

    attr_accessor :operator_name

    attr_accessor :source_network_affiliate_partner_id

    # Omit for country-grain inventory.
    attr_accessor :subnational_region_code

    attr_accessor :web_deep_link_url

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'android_deep_link_url' => :'android_deep_link_url',
        :'country_code' => :'country_code',
        :'ios_deep_link_url' => :'ios_deep_link_url',
        :'is_active' => :'is_active',
        :'offer_call_to_action' => :'offer_call_to_action',
        :'offer_campaign' => :'offer_campaign',
        :'offer_category_id' => :'offer_category_id',
        :'offer_display_bullets' => :'offer_display_bullets',
        :'offer_display_small_print' => :'offer_display_small_print',
        :'offer_ev_usd' => :'offer_ev_usd',
        :'offer_label' => :'offer_label',
        :'offer_priority' => :'offer_priority',
        :'offer_tagline' => :'offer_tagline',
        :'operator_id' => :'operator_id',
        :'operator_name' => :'operator_name',
        :'source_network_affiliate_partner_id' => :'source_network_affiliate_partner_id',
        :'subnational_region_code' => :'subnational_region_code',
        :'web_deep_link_url' => :'web_deep_link_url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'android_deep_link_url' => :'String',
        :'country_code' => :'String',
        :'ios_deep_link_url' => :'String',
        :'is_active' => :'Boolean',
        :'offer_call_to_action' => :'String',
        :'offer_campaign' => :'String',
        :'offer_category_id' => :'Integer',
        :'offer_display_bullets' => :'Array<String>',
        :'offer_display_small_print' => :'String',
        :'offer_ev_usd' => :'Float',
        :'offer_label' => :'String',
        :'offer_priority' => :'Integer',
        :'offer_tagline' => :'String',
        :'operator_id' => :'Integer',
        :'operator_name' => :'String',
        :'source_network_affiliate_partner_id' => :'Integer',
        :'subnational_region_code' => :'String',
        :'web_deep_link_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::V1AffiliatesLinksPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::V1AffiliatesLinksPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'android_deep_link_url')
        self.android_deep_link_url = attributes[:'android_deep_link_url']
      end

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      else
        self.country_code = 'US'
      end

      if attributes.key?(:'ios_deep_link_url')
        self.ios_deep_link_url = attributes[:'ios_deep_link_url']
      end

      if attributes.key?(:'is_active')
        self.is_active = attributes[:'is_active']
      else
        self.is_active = true
      end

      if attributes.key?(:'offer_call_to_action')
        self.offer_call_to_action = attributes[:'offer_call_to_action']
      end

      if attributes.key?(:'offer_campaign')
        self.offer_campaign = attributes[:'offer_campaign']
      end

      if attributes.key?(:'offer_category_id')
        self.offer_category_id = attributes[:'offer_category_id']
      else
        self.offer_category_id = nil
      end

      if attributes.key?(:'offer_display_bullets')
        if (value = attributes[:'offer_display_bullets']).is_a?(Array)
          self.offer_display_bullets = value
        end
      end

      if attributes.key?(:'offer_display_small_print')
        self.offer_display_small_print = attributes[:'offer_display_small_print']
      end

      if attributes.key?(:'offer_ev_usd')
        self.offer_ev_usd = attributes[:'offer_ev_usd']
      end

      if attributes.key?(:'offer_label')
        self.offer_label = attributes[:'offer_label']
      end

      if attributes.key?(:'offer_priority')
        self.offer_priority = attributes[:'offer_priority']
      end

      if attributes.key?(:'offer_tagline')
        self.offer_tagline = attributes[:'offer_tagline']
      end

      if attributes.key?(:'operator_id')
        self.operator_id = attributes[:'operator_id']
      end

      if attributes.key?(:'operator_name')
        self.operator_name = attributes[:'operator_name']
      end

      if attributes.key?(:'source_network_affiliate_partner_id')
        self.source_network_affiliate_partner_id = attributes[:'source_network_affiliate_partner_id']
      end

      if attributes.key?(:'subnational_region_code')
        self.subnational_region_code = attributes[:'subnational_region_code']
      end

      if attributes.key?(:'web_deep_link_url')
        self.web_deep_link_url = attributes[:'web_deep_link_url']
      else
        self.web_deep_link_url = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@country_code.nil? && @country_code.to_s.length > 2
        invalid_properties.push('invalid value for "country_code", the character length must be smaller than or equal to 2.')
      end

      if !@country_code.nil? && @country_code.to_s.length < 2
        invalid_properties.push('invalid value for "country_code", the character length must be greater than or equal to 2.')
      end

      if !@offer_campaign.nil? && @offer_campaign.to_s.length > 255
        invalid_properties.push('invalid value for "offer_campaign", the character length must be smaller than or equal to 255.')
      end

      if @offer_category_id.nil?
        invalid_properties.push('invalid value for "offer_category_id", offer_category_id cannot be nil.')
      end

      if !@offer_display_small_print.nil? && @offer_display_small_print.to_s.length > 255
        invalid_properties.push('invalid value for "offer_display_small_print", the character length must be smaller than or equal to 255.')
      end

      if !@offer_label.nil? && @offer_label.to_s.length > 255
        invalid_properties.push('invalid value for "offer_label", the character length must be smaller than or equal to 255.')
      end

      if !@offer_tagline.nil? && @offer_tagline.to_s.length > 255
        invalid_properties.push('invalid value for "offer_tagline", the character length must be smaller than or equal to 255.')
      end

      if !@subnational_region_code.nil? && @subnational_region_code.to_s.length > 10
        invalid_properties.push('invalid value for "subnational_region_code", the character length must be smaller than or equal to 10.')
      end

      if @web_deep_link_url.nil?
        invalid_properties.push('invalid value for "web_deep_link_url", web_deep_link_url cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@country_code.nil? && @country_code.to_s.length > 2
      return false if !@country_code.nil? && @country_code.to_s.length < 2
      return false if !@offer_campaign.nil? && @offer_campaign.to_s.length > 255
      return false if @offer_category_id.nil?
      return false if !@offer_display_small_print.nil? && @offer_display_small_print.to_s.length > 255
      return false if !@offer_label.nil? && @offer_label.to_s.length > 255
      return false if !@offer_tagline.nil? && @offer_tagline.to_s.length > 255
      return false if !@subnational_region_code.nil? && @subnational_region_code.to_s.length > 10
      return false if @web_deep_link_url.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] country_code Value to be assigned
    def country_code=(country_code)
      if country_code.nil?
        fail ArgumentError, 'country_code cannot be nil'
      end

      if country_code.to_s.length > 2
        fail ArgumentError, 'invalid value for "country_code", the character length must be smaller than or equal to 2.'
      end

      if country_code.to_s.length < 2
        fail ArgumentError, 'invalid value for "country_code", the character length must be greater than or equal to 2.'
      end

      @country_code = country_code
    end

    # Custom attribute writer method with validation
    # @param [Object] offer_campaign Value to be assigned
    def offer_campaign=(offer_campaign)
      if offer_campaign.nil?
        fail ArgumentError, 'offer_campaign cannot be nil'
      end

      if offer_campaign.to_s.length > 255
        fail ArgumentError, 'invalid value for "offer_campaign", the character length must be smaller than or equal to 255.'
      end

      @offer_campaign = offer_campaign
    end

    # Custom attribute writer method with validation
    # @param [Object] offer_category_id Value to be assigned
    def offer_category_id=(offer_category_id)
      if offer_category_id.nil?
        fail ArgumentError, 'offer_category_id cannot be nil'
      end

      @offer_category_id = offer_category_id
    end

    # Custom attribute writer method with validation
    # @param [Object] offer_display_small_print Value to be assigned
    def offer_display_small_print=(offer_display_small_print)
      if offer_display_small_print.nil?
        fail ArgumentError, 'offer_display_small_print cannot be nil'
      end

      if offer_display_small_print.to_s.length > 255
        fail ArgumentError, 'invalid value for "offer_display_small_print", the character length must be smaller than or equal to 255.'
      end

      @offer_display_small_print = offer_display_small_print
    end

    # Custom attribute writer method with validation
    # @param [Object] offer_label Value to be assigned
    def offer_label=(offer_label)
      if offer_label.nil?
        fail ArgumentError, 'offer_label cannot be nil'
      end

      if offer_label.to_s.length > 255
        fail ArgumentError, 'invalid value for "offer_label", the character length must be smaller than or equal to 255.'
      end

      @offer_label = offer_label
    end

    # Custom attribute writer method with validation
    # @param [Object] offer_tagline Value to be assigned
    def offer_tagline=(offer_tagline)
      if offer_tagline.nil?
        fail ArgumentError, 'offer_tagline cannot be nil'
      end

      if offer_tagline.to_s.length > 255
        fail ArgumentError, 'invalid value for "offer_tagline", the character length must be smaller than or equal to 255.'
      end

      @offer_tagline = offer_tagline
    end

    # Custom attribute writer method with validation
    # @param [Object] subnational_region_code Value to be assigned
    def subnational_region_code=(subnational_region_code)
      if subnational_region_code.nil?
        fail ArgumentError, 'subnational_region_code cannot be nil'
      end

      if subnational_region_code.to_s.length > 10
        fail ArgumentError, 'invalid value for "subnational_region_code", the character length must be smaller than or equal to 10.'
      end

      @subnational_region_code = subnational_region_code
    end

    # Custom attribute writer method with validation
    # @param [Object] web_deep_link_url Value to be assigned
    def web_deep_link_url=(web_deep_link_url)
      if web_deep_link_url.nil?
        fail ArgumentError, 'web_deep_link_url cannot be nil'
      end

      @web_deep_link_url = web_deep_link_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          android_deep_link_url == o.android_deep_link_url &&
          country_code == o.country_code &&
          ios_deep_link_url == o.ios_deep_link_url &&
          is_active == o.is_active &&
          offer_call_to_action == o.offer_call_to_action &&
          offer_campaign == o.offer_campaign &&
          offer_category_id == o.offer_category_id &&
          offer_display_bullets == o.offer_display_bullets &&
          offer_display_small_print == o.offer_display_small_print &&
          offer_ev_usd == o.offer_ev_usd &&
          offer_label == o.offer_label &&
          offer_priority == o.offer_priority &&
          offer_tagline == o.offer_tagline &&
          operator_id == o.operator_id &&
          operator_name == o.operator_name &&
          source_network_affiliate_partner_id == o.source_network_affiliate_partner_id &&
          subnational_region_code == o.subnational_region_code &&
          web_deep_link_url == o.web_deep_link_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [android_deep_link_url, country_code, ios_deep_link_url, is_active, offer_call_to_action, offer_campaign, offer_category_id, offer_display_bullets, offer_display_small_print, offer_ev_usd, offer_label, offer_priority, offer_tagline, operator_id, operator_name, source_network_affiliate_partner_id, subnational_region_code, web_deep_link_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
