=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  class V1AffiliatesEventsPostRequest < ApiModelBase
    attr_accessor :country_code

    attr_accessor :device_type

    attr_accessor :event_type

    attr_accessor :offer_campaign

    attr_accessor :offer_id

    attr_accessor :offer_label

    attr_accessor :operator_id

    attr_accessor :session_token

    attr_accessor :subnational_region_code

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'country_code' => :'country_code',
        :'device_type' => :'device_type',
        :'event_type' => :'event_type',
        :'offer_campaign' => :'offer_campaign',
        :'offer_id' => :'offer_id',
        :'offer_label' => :'offer_label',
        :'operator_id' => :'operator_id',
        :'session_token' => :'session_token',
        :'subnational_region_code' => :'subnational_region_code'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'country_code' => :'String',
        :'device_type' => :'String',
        :'event_type' => :'String',
        :'offer_campaign' => :'String',
        :'offer_id' => :'String',
        :'offer_label' => :'String',
        :'operator_id' => :'Integer',
        :'session_token' => :'String',
        :'subnational_region_code' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::V1AffiliatesEventsPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::V1AffiliatesEventsPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      else
        self.country_code = nil
      end

      if attributes.key?(:'device_type')
        self.device_type = attributes[:'device_type']
      end

      if attributes.key?(:'event_type')
        self.event_type = attributes[:'event_type']
      else
        self.event_type = nil
      end

      if attributes.key?(:'offer_campaign')
        self.offer_campaign = attributes[:'offer_campaign']
      end

      if attributes.key?(:'offer_id')
        self.offer_id = attributes[:'offer_id']
      else
        self.offer_id = nil
      end

      if attributes.key?(:'offer_label')
        self.offer_label = attributes[:'offer_label']
      end

      if attributes.key?(:'operator_id')
        self.operator_id = attributes[:'operator_id']
      else
        self.operator_id = nil
      end

      if attributes.key?(:'session_token')
        self.session_token = attributes[:'session_token']
      end

      if attributes.key?(:'subnational_region_code')
        self.subnational_region_code = attributes[:'subnational_region_code']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @country_code.nil?
        invalid_properties.push('invalid value for "country_code", country_code cannot be nil.')
      end

      if @country_code.to_s.length > 2
        invalid_properties.push('invalid value for "country_code", the character length must be smaller than or equal to 2.')
      end

      if @country_code.to_s.length < 2
        invalid_properties.push('invalid value for "country_code", the character length must be greater than or equal to 2.')
      end

      if @event_type.nil?
        invalid_properties.push('invalid value for "event_type", event_type cannot be nil.')
      end

      if !@offer_campaign.nil? && @offer_campaign.to_s.length > 255
        invalid_properties.push('invalid value for "offer_campaign", the character length must be smaller than or equal to 255.')
      end

      if @offer_id.nil?
        invalid_properties.push('invalid value for "offer_id", offer_id cannot be nil.')
      end

      if !@offer_label.nil? && @offer_label.to_s.length > 255
        invalid_properties.push('invalid value for "offer_label", the character length must be smaller than or equal to 255.')
      end

      if @operator_id.nil?
        invalid_properties.push('invalid value for "operator_id", operator_id cannot be nil.')
      end

      if @operator_id < 1
        invalid_properties.push('invalid value for "operator_id", must be greater than or equal to 1.')
      end

      if !@session_token.nil? && @session_token.to_s.length > 64
        invalid_properties.push('invalid value for "session_token", the character length must be smaller than or equal to 64.')
      end

      if !@subnational_region_code.nil? && @subnational_region_code.to_s.length > 10
        invalid_properties.push('invalid value for "subnational_region_code", the character length must be smaller than or equal to 10.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @country_code.nil?
      return false if @country_code.to_s.length > 2
      return false if @country_code.to_s.length < 2
      device_type_validator = EnumAttributeValidator.new('String', ["ios", "android", "desktop"])
      return false unless device_type_validator.valid?(@device_type)
      return false if @event_type.nil?
      event_type_validator = EnumAttributeValidator.new('String', ["impression", "click"])
      return false unless event_type_validator.valid?(@event_type)
      return false if !@offer_campaign.nil? && @offer_campaign.to_s.length > 255
      return false if @offer_id.nil?
      return false if !@offer_label.nil? && @offer_label.to_s.length > 255
      return false if @operator_id.nil?
      return false if @operator_id < 1
      return false if !@session_token.nil? && @session_token.to_s.length > 64
      return false if !@subnational_region_code.nil? && @subnational_region_code.to_s.length > 10
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] country_code Value to be assigned
    def country_code=(country_code)
      if country_code.nil?
        fail ArgumentError, 'country_code cannot be nil'
      end

      if country_code.to_s.length > 2
        fail ArgumentError, 'invalid value for "country_code", the character length must be smaller than or equal to 2.'
      end

      if country_code.to_s.length < 2
        fail ArgumentError, 'invalid value for "country_code", the character length must be greater than or equal to 2.'
      end

      @country_code = country_code
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] device_type Object to be assigned
    def device_type=(device_type)
      validator = EnumAttributeValidator.new('String', ["ios", "android", "desktop"])
      unless validator.valid?(device_type)
        fail ArgumentError, "invalid value for \"device_type\", must be one of #{validator.allowable_values}."
      end
      @device_type = device_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] event_type Object to be assigned
    def event_type=(event_type)
      validator = EnumAttributeValidator.new('String', ["impression", "click"])
      unless validator.valid?(event_type)
        fail ArgumentError, "invalid value for \"event_type\", must be one of #{validator.allowable_values}."
      end
      @event_type = event_type
    end

    # Custom attribute writer method with validation
    # @param [Object] offer_campaign Value to be assigned
    def offer_campaign=(offer_campaign)
      if offer_campaign.nil?
        fail ArgumentError, 'offer_campaign cannot be nil'
      end

      if offer_campaign.to_s.length > 255
        fail ArgumentError, 'invalid value for "offer_campaign", the character length must be smaller than or equal to 255.'
      end

      @offer_campaign = offer_campaign
    end

    # Custom attribute writer method with validation
    # @param [Object] offer_id Value to be assigned
    def offer_id=(offer_id)
      if offer_id.nil?
        fail ArgumentError, 'offer_id cannot be nil'
      end

      @offer_id = offer_id
    end

    # Custom attribute writer method with validation
    # @param [Object] offer_label Value to be assigned
    def offer_label=(offer_label)
      if offer_label.nil?
        fail ArgumentError, 'offer_label cannot be nil'
      end

      if offer_label.to_s.length > 255
        fail ArgumentError, 'invalid value for "offer_label", the character length must be smaller than or equal to 255.'
      end

      @offer_label = offer_label
    end

    # Custom attribute writer method with validation
    # @param [Object] operator_id Value to be assigned
    def operator_id=(operator_id)
      if operator_id.nil?
        fail ArgumentError, 'operator_id cannot be nil'
      end

      if operator_id < 1
        fail ArgumentError, 'invalid value for "operator_id", must be greater than or equal to 1.'
      end

      @operator_id = operator_id
    end

    # Custom attribute writer method with validation
    # @param [Object] session_token Value to be assigned
    def session_token=(session_token)
      if session_token.nil?
        fail ArgumentError, 'session_token cannot be nil'
      end

      if session_token.to_s.length > 64
        fail ArgumentError, 'invalid value for "session_token", the character length must be smaller than or equal to 64.'
      end

      @session_token = session_token
    end

    # Custom attribute writer method with validation
    # @param [Object] subnational_region_code Value to be assigned
    def subnational_region_code=(subnational_region_code)
      if subnational_region_code.nil?
        fail ArgumentError, 'subnational_region_code cannot be nil'
      end

      if subnational_region_code.to_s.length > 10
        fail ArgumentError, 'invalid value for "subnational_region_code", the character length must be smaller than or equal to 10.'
      end

      @subnational_region_code = subnational_region_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          country_code == o.country_code &&
          device_type == o.device_type &&
          event_type == o.event_type &&
          offer_campaign == o.offer_campaign &&
          offer_id == o.offer_id &&
          offer_label == o.offer_label &&
          operator_id == o.operator_id &&
          session_token == o.session_token &&
          subnational_region_code == o.subnational_region_code
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [country_code, device_type, event_type, offer_campaign, offer_id, offer_label, operator_id, session_token, subnational_region_code].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
