=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  class V1EventsUpcomingEventsPostRequest < ApiModelBase
    # Filter by event date (YYYY-MM-DD). Defaults to today (UTC).
    attr_accessor :event_date

    attr_accessor :league_id

    # League external key (e.g. 'nba', 'united-states.nba'). Alternative to league_id. If both are provided, league_id takes precedence.
    attr_accessor :league_key

    # Page number for pagination
    attr_accessor :page

    # Number of events per page
    attr_accessor :page_size

    attr_accessor :sport_id

    # Sport external key (e.g. 'american-football'). Alternative to sport_id. If both are provided, sport_id takes precedence.
    attr_accessor :sport_key

    # IANA timezone for date interpretation (e.g. 'UTC', 'America/New_York', 'Europe/London')
    attr_accessor :timezone

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'event_date' => :'event_date',
        :'league_id' => :'league_id',
        :'league_key' => :'league_key',
        :'page' => :'page',
        :'page_size' => :'page_size',
        :'sport_id' => :'sport_id',
        :'sport_key' => :'sport_key',
        :'timezone' => :'timezone'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'event_date' => :'Date',
        :'league_id' => :'Integer',
        :'league_key' => :'String',
        :'page' => :'Integer',
        :'page_size' => :'Integer',
        :'sport_id' => :'Integer',
        :'sport_key' => :'String',
        :'timezone' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::V1EventsUpcomingEventsPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::V1EventsUpcomingEventsPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'event_date')
        self.event_date = attributes[:'event_date']
      end

      if attributes.key?(:'league_id')
        self.league_id = attributes[:'league_id']
      end

      if attributes.key?(:'league_key')
        self.league_key = attributes[:'league_key']
      end

      if attributes.key?(:'page')
        self.page = attributes[:'page']
      else
        self.page = 1
      end

      if attributes.key?(:'page_size')
        self.page_size = attributes[:'page_size']
      else
        self.page_size = 100
      end

      if attributes.key?(:'sport_id')
        self.sport_id = attributes[:'sport_id']
      end

      if attributes.key?(:'sport_key')
        self.sport_key = attributes[:'sport_key']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      else
        self.timezone = 'UTC'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@league_id.nil? && @league_id < 1
        invalid_properties.push('invalid value for "league_id", must be greater than or equal to 1.')
      end

      if !@page.nil? && @page < 1
        invalid_properties.push('invalid value for "page", must be greater than or equal to 1.')
      end

      if !@page_size.nil? && @page_size > 100
        invalid_properties.push('invalid value for "page_size", must be smaller than or equal to 100.')
      end

      if !@page_size.nil? && @page_size < 1
        invalid_properties.push('invalid value for "page_size", must be greater than or equal to 1.')
      end

      if !@sport_id.nil? && @sport_id < 1
        invalid_properties.push('invalid value for "sport_id", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@league_id.nil? && @league_id < 1
      return false if !@page.nil? && @page < 1
      return false if !@page_size.nil? && @page_size > 100
      return false if !@page_size.nil? && @page_size < 1
      return false if !@sport_id.nil? && @sport_id < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] league_id Value to be assigned
    def league_id=(league_id)
      if league_id.nil?
        fail ArgumentError, 'league_id cannot be nil'
      end

      if league_id < 1
        fail ArgumentError, 'invalid value for "league_id", must be greater than or equal to 1.'
      end

      @league_id = league_id
    end

    # Custom attribute writer method with validation
    # @param [Object] page Value to be assigned
    def page=(page)
      if page.nil?
        fail ArgumentError, 'page cannot be nil'
      end

      if page < 1
        fail ArgumentError, 'invalid value for "page", must be greater than or equal to 1.'
      end

      @page = page
    end

    # Custom attribute writer method with validation
    # @param [Object] page_size Value to be assigned
    def page_size=(page_size)
      if page_size.nil?
        fail ArgumentError, 'page_size cannot be nil'
      end

      if page_size > 100
        fail ArgumentError, 'invalid value for "page_size", must be smaller than or equal to 100.'
      end

      if page_size < 1
        fail ArgumentError, 'invalid value for "page_size", must be greater than or equal to 1.'
      end

      @page_size = page_size
    end

    # Custom attribute writer method with validation
    # @param [Object] sport_id Value to be assigned
    def sport_id=(sport_id)
      if sport_id.nil?
        fail ArgumentError, 'sport_id cannot be nil'
      end

      if sport_id < 1
        fail ArgumentError, 'invalid value for "sport_id", must be greater than or equal to 1.'
      end

      @sport_id = sport_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          event_date == o.event_date &&
          league_id == o.league_id &&
          league_key == o.league_key &&
          page == o.page &&
          page_size == o.page_size &&
          sport_id == o.sport_id &&
          sport_key == o.sport_key &&
          timezone == o.timezone
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [event_date, league_id, league_key, page, page_size, sport_id, sport_key, timezone].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
