=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  class V1TrendsFlowsByIdPostRequest < ApiModelBase
    # Sub-type for fact flows. Defaults to 'base' if omitted.
    attr_accessor :fact_flow_type

    # Array of flow IDs to retrieve
    attr_accessor :flow_ids

    attr_accessor :flow_type

    # When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
    attr_accessor :use_cartoon_images

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'fact_flow_type' => :'fact_flow_type',
        :'flow_ids' => :'flow_ids',
        :'flow_type' => :'flow_type',
        :'use_cartoon_images' => :'use_cartoon_images'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'fact_flow_type' => :'String',
        :'flow_ids' => :'Array<Integer>',
        :'flow_type' => :'String',
        :'use_cartoon_images' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::V1TrendsFlowsByIdPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::V1TrendsFlowsByIdPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'fact_flow_type')
        self.fact_flow_type = attributes[:'fact_flow_type']
      end

      if attributes.key?(:'flow_ids')
        if (value = attributes[:'flow_ids']).is_a?(Array)
          self.flow_ids = value
        end
      else
        self.flow_ids = nil
      end

      if attributes.key?(:'flow_type')
        self.flow_type = attributes[:'flow_type']
      else
        self.flow_type = nil
      end

      if attributes.key?(:'use_cartoon_images')
        self.use_cartoon_images = attributes[:'use_cartoon_images']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @flow_ids.nil?
        invalid_properties.push('invalid value for "flow_ids", flow_ids cannot be nil.')
      end

      if @flow_ids.length < 1
        invalid_properties.push('invalid value for "flow_ids", number of items must be greater than or equal to 1.')
      end

      if @flow_type.nil?
        invalid_properties.push('invalid value for "flow_type", flow_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      fact_flow_type_validator = EnumAttributeValidator.new('String', ["base", "expanded"])
      return false unless fact_flow_type_validator.valid?(@fact_flow_type)
      return false if @flow_ids.nil?
      return false if @flow_ids.length < 1
      return false if @flow_type.nil?
      flow_type_validator = EnumAttributeValidator.new('String', ["fact_flow", "fun_flow", "fact_flow_parlay", "fun_flow_parlay", "plain_flow_parlay"])
      return false unless flow_type_validator.valid?(@flow_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] fact_flow_type Object to be assigned
    def fact_flow_type=(fact_flow_type)
      validator = EnumAttributeValidator.new('String', ["base", "expanded"])
      unless validator.valid?(fact_flow_type)
        fail ArgumentError, "invalid value for \"fact_flow_type\", must be one of #{validator.allowable_values}."
      end
      @fact_flow_type = fact_flow_type
    end

    # Custom attribute writer method with validation
    # @param [Object] flow_ids Value to be assigned
    def flow_ids=(flow_ids)
      if flow_ids.nil?
        fail ArgumentError, 'flow_ids cannot be nil'
      end

      if flow_ids.length < 1
        fail ArgumentError, 'invalid value for "flow_ids", number of items must be greater than or equal to 1.'
      end

      @flow_ids = flow_ids
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] flow_type Object to be assigned
    def flow_type=(flow_type)
      validator = EnumAttributeValidator.new('String', ["fact_flow", "fun_flow", "fact_flow_parlay", "fun_flow_parlay", "plain_flow_parlay"])
      unless validator.valid?(flow_type)
        fail ArgumentError, "invalid value for \"flow_type\", must be one of #{validator.allowable_values}."
      end
      @flow_type = flow_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          fact_flow_type == o.fact_flow_type &&
          flow_ids == o.flow_ids &&
          flow_type == o.flow_type &&
          use_cartoon_images == o.use_cartoon_images
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [fact_flow_type, flow_ids, flow_type, use_cartoon_images].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
