=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  class V1TrendsByBettingMarketPositionPostRequest < ApiModelBase
    # Array of event betting market position IDs
    attr_accessor :event_betting_market_position_ids

    # Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
    attr_accessor :odds_format

    # Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.
    attr_accessor :product_mode

    # When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
    attr_accessor :use_cartoon_images

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'event_betting_market_position_ids' => :'event_betting_market_position_ids',
        :'odds_format' => :'odds_format',
        :'product_mode' => :'product_mode',
        :'use_cartoon_images' => :'use_cartoon_images'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'event_betting_market_position_ids' => :'Array<Integer>',
        :'odds_format' => :'String',
        :'product_mode' => :'String',
        :'use_cartoon_images' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::V1TrendsByBettingMarketPositionPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::V1TrendsByBettingMarketPositionPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'event_betting_market_position_ids')
        if (value = attributes[:'event_betting_market_position_ids']).is_a?(Array)
          self.event_betting_market_position_ids = value
        end
      else
        self.event_betting_market_position_ids = nil
      end

      if attributes.key?(:'odds_format')
        self.odds_format = attributes[:'odds_format']
      end

      if attributes.key?(:'product_mode')
        self.product_mode = attributes[:'product_mode']
      end

      if attributes.key?(:'use_cartoon_images')
        self.use_cartoon_images = attributes[:'use_cartoon_images']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @event_betting_market_position_ids.nil?
        invalid_properties.push('invalid value for "event_betting_market_position_ids", event_betting_market_position_ids cannot be nil.')
      end

      if @event_betting_market_position_ids.length < 1
        invalid_properties.push('invalid value for "event_betting_market_position_ids", number of items must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @event_betting_market_position_ids.nil?
      return false if @event_betting_market_position_ids.length < 1
      odds_format_validator = EnumAttributeValidator.new('String', ["american", "decimal", "fractional", "multiplier", "percent"])
      return false unless odds_format_validator.valid?(@odds_format)
      product_mode_validator = EnumAttributeValidator.new('String', ["sportsbook", "dfs", "prediction_market"])
      return false unless product_mode_validator.valid?(@product_mode)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] event_betting_market_position_ids Value to be assigned
    def event_betting_market_position_ids=(event_betting_market_position_ids)
      if event_betting_market_position_ids.nil?
        fail ArgumentError, 'event_betting_market_position_ids cannot be nil'
      end

      if event_betting_market_position_ids.length < 1
        fail ArgumentError, 'invalid value for "event_betting_market_position_ids", number of items must be greater than or equal to 1.'
      end

      @event_betting_market_position_ids = event_betting_market_position_ids
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] odds_format Object to be assigned
    def odds_format=(odds_format)
      validator = EnumAttributeValidator.new('String', ["american", "decimal", "fractional", "multiplier", "percent"])
      unless validator.valid?(odds_format)
        fail ArgumentError, "invalid value for \"odds_format\", must be one of #{validator.allowable_values}."
      end
      @odds_format = odds_format
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] product_mode Object to be assigned
    def product_mode=(product_mode)
      validator = EnumAttributeValidator.new('String', ["sportsbook", "dfs", "prediction_market"])
      unless validator.valid?(product_mode)
        fail ArgumentError, "invalid value for \"product_mode\", must be one of #{validator.allowable_values}."
      end
      @product_mode = product_mode
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          event_betting_market_position_ids == o.event_betting_market_position_ids &&
          odds_format == o.odds_format &&
          product_mode == o.product_mode &&
          use_cartoon_images == o.use_cartoon_images
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [event_betting_market_position_ids, odds_format, product_mode, use_cartoon_images].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
