=begin
#Odditt B2B Public API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module OddittApiClient
  class V1TrendsFlowsPostRequest < ApiModelBase
    # Filter by bet type. If omitted, returns mixed singles and parlays.
    attr_accessor :bet_type

    # Deprecated — use `betting_market_category_ids` instead (e.g. Shooting Props, Game Props etc.). A bare `betting_market_category_id` is treated as `betting_market_category_ids: [betting_market_category_id]`.
    attr_accessor :betting_market_category_id

    # Filter by one or more betting market category IDs (e.g. Shooting Props, Game Props etc.). Empty array = no filter.
    attr_accessor :betting_market_category_ids

    # Filter by betting market entity type
    attr_accessor :betting_market_entity_type

    # Filter by betting market IDs
    attr_accessor :betting_market_ids

    # Deprecated — use `betting_market_position_ids` instead. A bare `betting_market_position_id` is treated as `betting_market_position_ids: [betting_market_position_id]`.
    attr_accessor :betting_market_position_id

    # Filter by one or more betting market position IDs. Empty array = no filter.
    attr_accessor :betting_market_position_ids

    # Deprecated — use `event_ids` instead. A bare `event_id` is treated as `event_ids: [event_id]`.
    attr_accessor :event_id

    # Filter by one or more event IDs. Empty array = no filter.
    attr_accessor :event_ids

    # Filter events starting on or after this value. Accepts a date ('2026-04-19') or full ISO 8601 timestamp ('2026-04-19T00:00:00Z').
    attr_accessor :event_start_date_from

    # Filter events starting on or before this value. Accepts a date ('2026-04-26') or full ISO 8601 timestamp ('2026-04-26T23:59:59Z').
    attr_accessor :event_start_date_to

    # Sub-type for fact flows. Defaults to 'base' if omitted.
    attr_accessor :fact_flow_type

    # Type of flow to return. 'plain' only returns parlays.
    attr_accessor :flow_type

    # Filter by focus entity type ID
    attr_accessor :focus_entity_type_id

    # When true, include full hit rate data in response
    attr_accessor :full_hit_rate

    # When false, exclude alt lines. Defaults to true.
    attr_accessor :include_alt_lines

    # When true, returns operator-specific odds and deeplink URLs (bet_ios_deep_link_url, bet_android_deep_link_url, bet_web_deep_link_url) for each flow. Requires exactly one operator_id in operator_ids.
    attr_accessor :include_deeplinks

    # When true, return only basic trends (omit fact flows with conditions)
    attr_accessor :include_only_basic_trends

    # When true, include star sign/horoscope content in flows
    attr_accessor :include_star_sign_content

    # Deprecated — use `league_ids` instead. A bare `league_id` is treated as `league_ids: [league_id]`.
    attr_accessor :league_id

    # Filter by one or more league IDs. Empty array = no filter.
    attr_accessor :league_ids

    # League external key (e.g. 'nba', 'united-states.nba'). Format: {league_key} or {country_key}.{league_key}. Alternative to league_id. If both are provided, league_id takes precedence.
    attr_accessor :league_key

    # Filter by likelihood category
    attr_accessor :likelihood_type

    # Maximum hit rate threshold filter (0-100)
    attr_accessor :max_hit_rate_threshold

    # Maximum implied probability threshold filter
    attr_accessor :max_implied_probability_threshold

    # Minimum hit rate threshold filter (0-100)
    attr_accessor :min_hit_rate_threshold

    # Minimum implied probability threshold filter
    attr_accessor :min_implied_probability_threshold

    # Odds display format. Defaults per product_mode (dfs→multiplier, prediction_market→percent, else american).
    attr_accessor :odds_format

    # Filter by operator IDs
    attr_accessor :operator_ids

    # Filter by operator external keys (e.g. 'draftkings'). Format: {operator_key}. Resolved IDs are merged with operator_ids.
    attr_accessor :operator_keys

    attr_accessor :page

    attr_accessor :page_size

    # Deprecated — use `player_ids` instead. A bare `player_id` is treated as `player_ids: [player_id]`.
    attr_accessor :player_id

    # Filter by one or more player IDs. Empty array = no filter.
    attr_accessor :player_ids

    # Player external key (e.g. 'nikola-vucevic', 'chicago-bulls.tre-jones', 'nba.boston-celtics.nikola-vucevic'). Format: {player_key} or {team_key}.{player_key} or {league_key}.{team_key}.{player_key}. Alternative to player_id. If both are provided, player_id takes precedence.
    attr_accessor :player_key

    # Display mode. dfs rewrites stat lines to MORE/LESS; on the paginated flows endpoints it also auto-filters to over/under player props (entity_type=player, positions [4,5]) unless an entity/position filter is set.
    attr_accessor :product_mode

    # Filter by split type (overs or unders)
    attr_accessor :split_type

    # Deprecated — use `sport_ids` instead. A bare `sport_id` is treated as `sport_ids: [sport_id]`.
    attr_accessor :sport_id

    # Filter by one or more sport IDs. Empty array = no filter.
    attr_accessor :sport_ids

    # Sport external key (e.g. 'american-football'). Format: {sport_key}. Alternative to sport_id. If both are provided, sport_id takes precedence.
    attr_accessor :sport_key

    # When true, only return flows for events starting soon
    attr_accessor :starting_soon

    # Deprecated — use `team_ids` instead. A bare `team_id` is treated as `team_ids: [team_id]`.
    attr_accessor :team_id

    # Filter by one or more team IDs. Empty array = no filter.
    attr_accessor :team_ids

    # Team external key (e.g. 'new-england-patriots', 'nfl.new-england-patriots'). Format: {team_key} or {league_key}.{team_key}. Alternative to team_id. If both are provided, team_id takes precedence.
    attr_accessor :team_key

    # Team split filter value
    attr_accessor :team_split

    # When true, the logo fields on each flow, leg, and multi-trend slot (default_logo_url, logo_url_1, logo_url_2) are replaced with cartoon-jersey image URLs derived from the relevant team, player, or league. When false or omitted, the original logo URLs are returned. Defaults to false.
    attr_accessor :use_cartoon_images

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'bet_type' => :'bet_type',
        :'betting_market_category_id' => :'betting_market_category_id',
        :'betting_market_category_ids' => :'betting_market_category_ids',
        :'betting_market_entity_type' => :'betting_market_entity_type',
        :'betting_market_ids' => :'betting_market_ids',
        :'betting_market_position_id' => :'betting_market_position_id',
        :'betting_market_position_ids' => :'betting_market_position_ids',
        :'event_id' => :'event_id',
        :'event_ids' => :'event_ids',
        :'event_start_date_from' => :'event_start_date_from',
        :'event_start_date_to' => :'event_start_date_to',
        :'fact_flow_type' => :'fact_flow_type',
        :'flow_type' => :'flow_type',
        :'focus_entity_type_id' => :'focus_entity_type_id',
        :'full_hit_rate' => :'full_hit_rate',
        :'include_alt_lines' => :'include_alt_lines',
        :'include_deeplinks' => :'include_deeplinks',
        :'include_only_basic_trends' => :'include_only_basic_trends',
        :'include_star_sign_content' => :'include_star_sign_content',
        :'league_id' => :'league_id',
        :'league_ids' => :'league_ids',
        :'league_key' => :'league_key',
        :'likelihood_type' => :'likelihood_type',
        :'max_hit_rate_threshold' => :'max_hit_rate_threshold',
        :'max_implied_probability_threshold' => :'max_implied_probability_threshold',
        :'min_hit_rate_threshold' => :'min_hit_rate_threshold',
        :'min_implied_probability_threshold' => :'min_implied_probability_threshold',
        :'odds_format' => :'odds_format',
        :'operator_ids' => :'operator_ids',
        :'operator_keys' => :'operator_keys',
        :'page' => :'page',
        :'page_size' => :'page_size',
        :'player_id' => :'player_id',
        :'player_ids' => :'player_ids',
        :'player_key' => :'player_key',
        :'product_mode' => :'product_mode',
        :'split_type' => :'split_type',
        :'sport_id' => :'sport_id',
        :'sport_ids' => :'sport_ids',
        :'sport_key' => :'sport_key',
        :'starting_soon' => :'starting_soon',
        :'team_id' => :'team_id',
        :'team_ids' => :'team_ids',
        :'team_key' => :'team_key',
        :'team_split' => :'team_split',
        :'use_cartoon_images' => :'use_cartoon_images'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'bet_type' => :'String',
        :'betting_market_category_id' => :'Integer',
        :'betting_market_category_ids' => :'Array<Integer>',
        :'betting_market_entity_type' => :'String',
        :'betting_market_ids' => :'Array<Integer>',
        :'betting_market_position_id' => :'Integer',
        :'betting_market_position_ids' => :'Array<Integer>',
        :'event_id' => :'Integer',
        :'event_ids' => :'Array<Integer>',
        :'event_start_date_from' => :'Time',
        :'event_start_date_to' => :'Time',
        :'fact_flow_type' => :'String',
        :'flow_type' => :'String',
        :'focus_entity_type_id' => :'Integer',
        :'full_hit_rate' => :'Boolean',
        :'include_alt_lines' => :'Boolean',
        :'include_deeplinks' => :'Boolean',
        :'include_only_basic_trends' => :'Boolean',
        :'include_star_sign_content' => :'Boolean',
        :'league_id' => :'Integer',
        :'league_ids' => :'Array<Integer>',
        :'league_key' => :'String',
        :'likelihood_type' => :'String',
        :'max_hit_rate_threshold' => :'Integer',
        :'max_implied_probability_threshold' => :'Float',
        :'min_hit_rate_threshold' => :'Integer',
        :'min_implied_probability_threshold' => :'Float',
        :'odds_format' => :'String',
        :'operator_ids' => :'Array<Integer>',
        :'operator_keys' => :'Array<String>',
        :'page' => :'Integer',
        :'page_size' => :'Integer',
        :'player_id' => :'Integer',
        :'player_ids' => :'Array<Integer>',
        :'player_key' => :'String',
        :'product_mode' => :'String',
        :'split_type' => :'String',
        :'sport_id' => :'Integer',
        :'sport_ids' => :'Array<Integer>',
        :'sport_key' => :'String',
        :'starting_soon' => :'Boolean',
        :'team_id' => :'Integer',
        :'team_ids' => :'Array<Integer>',
        :'team_key' => :'String',
        :'team_split' => :'String',
        :'use_cartoon_images' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OddittApiClient::V1TrendsFlowsPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OddittApiClient::V1TrendsFlowsPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'bet_type')
        self.bet_type = attributes[:'bet_type']
      end

      if attributes.key?(:'betting_market_category_id')
        self.betting_market_category_id = attributes[:'betting_market_category_id']
      end

      if attributes.key?(:'betting_market_category_ids')
        if (value = attributes[:'betting_market_category_ids']).is_a?(Array)
          self.betting_market_category_ids = value
        end
      end

      if attributes.key?(:'betting_market_entity_type')
        self.betting_market_entity_type = attributes[:'betting_market_entity_type']
      end

      if attributes.key?(:'betting_market_ids')
        if (value = attributes[:'betting_market_ids']).is_a?(Array)
          self.betting_market_ids = value
        end
      end

      if attributes.key?(:'betting_market_position_id')
        self.betting_market_position_id = attributes[:'betting_market_position_id']
      end

      if attributes.key?(:'betting_market_position_ids')
        if (value = attributes[:'betting_market_position_ids']).is_a?(Array)
          self.betting_market_position_ids = value
        end
      end

      if attributes.key?(:'event_id')
        self.event_id = attributes[:'event_id']
      end

      if attributes.key?(:'event_ids')
        if (value = attributes[:'event_ids']).is_a?(Array)
          self.event_ids = value
        end
      end

      if attributes.key?(:'event_start_date_from')
        self.event_start_date_from = attributes[:'event_start_date_from']
      end

      if attributes.key?(:'event_start_date_to')
        self.event_start_date_to = attributes[:'event_start_date_to']
      end

      if attributes.key?(:'fact_flow_type')
        self.fact_flow_type = attributes[:'fact_flow_type']
      end

      if attributes.key?(:'flow_type')
        self.flow_type = attributes[:'flow_type']
      end

      if attributes.key?(:'focus_entity_type_id')
        self.focus_entity_type_id = attributes[:'focus_entity_type_id']
      end

      if attributes.key?(:'full_hit_rate')
        self.full_hit_rate = attributes[:'full_hit_rate']
      end

      if attributes.key?(:'include_alt_lines')
        self.include_alt_lines = attributes[:'include_alt_lines']
      end

      if attributes.key?(:'include_deeplinks')
        self.include_deeplinks = attributes[:'include_deeplinks']
      end

      if attributes.key?(:'include_only_basic_trends')
        self.include_only_basic_trends = attributes[:'include_only_basic_trends']
      end

      if attributes.key?(:'include_star_sign_content')
        self.include_star_sign_content = attributes[:'include_star_sign_content']
      end

      if attributes.key?(:'league_id')
        self.league_id = attributes[:'league_id']
      end

      if attributes.key?(:'league_ids')
        if (value = attributes[:'league_ids']).is_a?(Array)
          self.league_ids = value
        end
      end

      if attributes.key?(:'league_key')
        self.league_key = attributes[:'league_key']
      end

      if attributes.key?(:'likelihood_type')
        self.likelihood_type = attributes[:'likelihood_type']
      end

      if attributes.key?(:'max_hit_rate_threshold')
        self.max_hit_rate_threshold = attributes[:'max_hit_rate_threshold']
      end

      if attributes.key?(:'max_implied_probability_threshold')
        self.max_implied_probability_threshold = attributes[:'max_implied_probability_threshold']
      end

      if attributes.key?(:'min_hit_rate_threshold')
        self.min_hit_rate_threshold = attributes[:'min_hit_rate_threshold']
      end

      if attributes.key?(:'min_implied_probability_threshold')
        self.min_implied_probability_threshold = attributes[:'min_implied_probability_threshold']
      end

      if attributes.key?(:'odds_format')
        self.odds_format = attributes[:'odds_format']
      end

      if attributes.key?(:'operator_ids')
        if (value = attributes[:'operator_ids']).is_a?(Array)
          self.operator_ids = value
        end
      end

      if attributes.key?(:'operator_keys')
        if (value = attributes[:'operator_keys']).is_a?(Array)
          self.operator_keys = value
        end
      end

      if attributes.key?(:'page')
        self.page = attributes[:'page']
      end

      if attributes.key?(:'page_size')
        self.page_size = attributes[:'page_size']
      end

      if attributes.key?(:'player_id')
        self.player_id = attributes[:'player_id']
      end

      if attributes.key?(:'player_ids')
        if (value = attributes[:'player_ids']).is_a?(Array)
          self.player_ids = value
        end
      end

      if attributes.key?(:'player_key')
        self.player_key = attributes[:'player_key']
      end

      if attributes.key?(:'product_mode')
        self.product_mode = attributes[:'product_mode']
      end

      if attributes.key?(:'split_type')
        self.split_type = attributes[:'split_type']
      end

      if attributes.key?(:'sport_id')
        self.sport_id = attributes[:'sport_id']
      end

      if attributes.key?(:'sport_ids')
        if (value = attributes[:'sport_ids']).is_a?(Array)
          self.sport_ids = value
        end
      end

      if attributes.key?(:'sport_key')
        self.sport_key = attributes[:'sport_key']
      end

      if attributes.key?(:'starting_soon')
        self.starting_soon = attributes[:'starting_soon']
      end

      if attributes.key?(:'team_id')
        self.team_id = attributes[:'team_id']
      end

      if attributes.key?(:'team_ids')
        if (value = attributes[:'team_ids']).is_a?(Array)
          self.team_ids = value
        end
      end

      if attributes.key?(:'team_key')
        self.team_key = attributes[:'team_key']
      end

      if attributes.key?(:'team_split')
        self.team_split = attributes[:'team_split']
      end

      if attributes.key?(:'use_cartoon_images')
        self.use_cartoon_images = attributes[:'use_cartoon_images']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@betting_market_category_id.nil? && @betting_market_category_id < 1
        invalid_properties.push('invalid value for "betting_market_category_id", must be greater than or equal to 1.')
      end

      if !@betting_market_position_id.nil? && @betting_market_position_id < 1
        invalid_properties.push('invalid value for "betting_market_position_id", must be greater than or equal to 1.')
      end

      if !@event_id.nil? && @event_id < 1
        invalid_properties.push('invalid value for "event_id", must be greater than or equal to 1.')
      end

      if !@focus_entity_type_id.nil? && @focus_entity_type_id < 1
        invalid_properties.push('invalid value for "focus_entity_type_id", must be greater than or equal to 1.')
      end

      if !@league_id.nil? && @league_id < 1
        invalid_properties.push('invalid value for "league_id", must be greater than or equal to 1.')
      end

      if !@max_hit_rate_threshold.nil? && @max_hit_rate_threshold > 100
        invalid_properties.push('invalid value for "max_hit_rate_threshold", must be smaller than or equal to 100.')
      end

      if !@max_hit_rate_threshold.nil? && @max_hit_rate_threshold < 0
        invalid_properties.push('invalid value for "max_hit_rate_threshold", must be greater than or equal to 0.')
      end

      if !@min_hit_rate_threshold.nil? && @min_hit_rate_threshold > 100
        invalid_properties.push('invalid value for "min_hit_rate_threshold", must be smaller than or equal to 100.')
      end

      if !@min_hit_rate_threshold.nil? && @min_hit_rate_threshold < 0
        invalid_properties.push('invalid value for "min_hit_rate_threshold", must be greater than or equal to 0.')
      end

      if !@page.nil? && @page < 1
        invalid_properties.push('invalid value for "page", must be greater than or equal to 1.')
      end

      if !@page_size.nil? && @page_size > 25
        invalid_properties.push('invalid value for "page_size", must be smaller than or equal to 25.')
      end

      if !@page_size.nil? && @page_size < 1
        invalid_properties.push('invalid value for "page_size", must be greater than or equal to 1.')
      end

      if !@player_id.nil? && @player_id < 1
        invalid_properties.push('invalid value for "player_id", must be greater than or equal to 1.')
      end

      if !@sport_id.nil? && @sport_id < 1
        invalid_properties.push('invalid value for "sport_id", must be greater than or equal to 1.')
      end

      if !@team_id.nil? && @team_id < 1
        invalid_properties.push('invalid value for "team_id", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      bet_type_validator = EnumAttributeValidator.new('String', ["singles", "parlay", "same_game_parlay"])
      return false unless bet_type_validator.valid?(@bet_type)
      return false if !@betting_market_category_id.nil? && @betting_market_category_id < 1
      betting_market_entity_type_validator = EnumAttributeValidator.new('String', ["player", "team", "event"])
      return false unless betting_market_entity_type_validator.valid?(@betting_market_entity_type)
      return false if !@betting_market_position_id.nil? && @betting_market_position_id < 1
      return false if !@event_id.nil? && @event_id < 1
      fact_flow_type_validator = EnumAttributeValidator.new('String', ["base", "expanded", "multi"])
      return false unless fact_flow_type_validator.valid?(@fact_flow_type)
      flow_type_validator = EnumAttributeValidator.new('String', ["fact", "fun", "plain"])
      return false unless flow_type_validator.valid?(@flow_type)
      return false if !@focus_entity_type_id.nil? && @focus_entity_type_id < 1
      return false if !@league_id.nil? && @league_id < 1
      likelihood_type_validator = EnumAttributeValidator.new('String', ["likely", "possible", "longshot"])
      return false unless likelihood_type_validator.valid?(@likelihood_type)
      return false if !@max_hit_rate_threshold.nil? && @max_hit_rate_threshold > 100
      return false if !@max_hit_rate_threshold.nil? && @max_hit_rate_threshold < 0
      return false if !@min_hit_rate_threshold.nil? && @min_hit_rate_threshold > 100
      return false if !@min_hit_rate_threshold.nil? && @min_hit_rate_threshold < 0
      odds_format_validator = EnumAttributeValidator.new('String', ["american", "decimal", "fractional", "multiplier", "percent"])
      return false unless odds_format_validator.valid?(@odds_format)
      return false if !@page.nil? && @page < 1
      return false if !@page_size.nil? && @page_size > 25
      return false if !@page_size.nil? && @page_size < 1
      return false if !@player_id.nil? && @player_id < 1
      product_mode_validator = EnumAttributeValidator.new('String', ["sportsbook", "dfs", "prediction_market"])
      return false unless product_mode_validator.valid?(@product_mode)
      split_type_validator = EnumAttributeValidator.new('String', ["overs", "unders"])
      return false unless split_type_validator.valid?(@split_type)
      return false if !@sport_id.nil? && @sport_id < 1
      return false if !@team_id.nil? && @team_id < 1
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] bet_type Object to be assigned
    def bet_type=(bet_type)
      validator = EnumAttributeValidator.new('String', ["singles", "parlay", "same_game_parlay"])
      unless validator.valid?(bet_type)
        fail ArgumentError, "invalid value for \"bet_type\", must be one of #{validator.allowable_values}."
      end
      @bet_type = bet_type
    end

    # Custom attribute writer method with validation
    # @param [Object] betting_market_category_id Value to be assigned
    def betting_market_category_id=(betting_market_category_id)
      if betting_market_category_id.nil?
        fail ArgumentError, 'betting_market_category_id cannot be nil'
      end

      if betting_market_category_id < 1
        fail ArgumentError, 'invalid value for "betting_market_category_id", must be greater than or equal to 1.'
      end

      @betting_market_category_id = betting_market_category_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] betting_market_entity_type Object to be assigned
    def betting_market_entity_type=(betting_market_entity_type)
      validator = EnumAttributeValidator.new('String', ["player", "team", "event"])
      unless validator.valid?(betting_market_entity_type)
        fail ArgumentError, "invalid value for \"betting_market_entity_type\", must be one of #{validator.allowable_values}."
      end
      @betting_market_entity_type = betting_market_entity_type
    end

    # Custom attribute writer method with validation
    # @param [Object] betting_market_position_id Value to be assigned
    def betting_market_position_id=(betting_market_position_id)
      if betting_market_position_id.nil?
        fail ArgumentError, 'betting_market_position_id cannot be nil'
      end

      if betting_market_position_id < 1
        fail ArgumentError, 'invalid value for "betting_market_position_id", must be greater than or equal to 1.'
      end

      @betting_market_position_id = betting_market_position_id
    end

    # Custom attribute writer method with validation
    # @param [Object] event_id Value to be assigned
    def event_id=(event_id)
      if event_id.nil?
        fail ArgumentError, 'event_id cannot be nil'
      end

      if event_id < 1
        fail ArgumentError, 'invalid value for "event_id", must be greater than or equal to 1.'
      end

      @event_id = event_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] fact_flow_type Object to be assigned
    def fact_flow_type=(fact_flow_type)
      validator = EnumAttributeValidator.new('String', ["base", "expanded", "multi"])
      unless validator.valid?(fact_flow_type)
        fail ArgumentError, "invalid value for \"fact_flow_type\", must be one of #{validator.allowable_values}."
      end
      @fact_flow_type = fact_flow_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] flow_type Object to be assigned
    def flow_type=(flow_type)
      validator = EnumAttributeValidator.new('String', ["fact", "fun", "plain"])
      unless validator.valid?(flow_type)
        fail ArgumentError, "invalid value for \"flow_type\", must be one of #{validator.allowable_values}."
      end
      @flow_type = flow_type
    end

    # Custom attribute writer method with validation
    # @param [Object] focus_entity_type_id Value to be assigned
    def focus_entity_type_id=(focus_entity_type_id)
      if focus_entity_type_id.nil?
        fail ArgumentError, 'focus_entity_type_id cannot be nil'
      end

      if focus_entity_type_id < 1
        fail ArgumentError, 'invalid value for "focus_entity_type_id", must be greater than or equal to 1.'
      end

      @focus_entity_type_id = focus_entity_type_id
    end

    # Custom attribute writer method with validation
    # @param [Object] league_id Value to be assigned
    def league_id=(league_id)
      if league_id.nil?
        fail ArgumentError, 'league_id cannot be nil'
      end

      if league_id < 1
        fail ArgumentError, 'invalid value for "league_id", must be greater than or equal to 1.'
      end

      @league_id = league_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] likelihood_type Object to be assigned
    def likelihood_type=(likelihood_type)
      validator = EnumAttributeValidator.new('String', ["likely", "possible", "longshot"])
      unless validator.valid?(likelihood_type)
        fail ArgumentError, "invalid value for \"likelihood_type\", must be one of #{validator.allowable_values}."
      end
      @likelihood_type = likelihood_type
    end

    # Custom attribute writer method with validation
    # @param [Object] max_hit_rate_threshold Value to be assigned
    def max_hit_rate_threshold=(max_hit_rate_threshold)
      if max_hit_rate_threshold.nil?
        fail ArgumentError, 'max_hit_rate_threshold cannot be nil'
      end

      if max_hit_rate_threshold > 100
        fail ArgumentError, 'invalid value for "max_hit_rate_threshold", must be smaller than or equal to 100.'
      end

      if max_hit_rate_threshold < 0
        fail ArgumentError, 'invalid value for "max_hit_rate_threshold", must be greater than or equal to 0.'
      end

      @max_hit_rate_threshold = max_hit_rate_threshold
    end

    # Custom attribute writer method with validation
    # @param [Object] min_hit_rate_threshold Value to be assigned
    def min_hit_rate_threshold=(min_hit_rate_threshold)
      if min_hit_rate_threshold.nil?
        fail ArgumentError, 'min_hit_rate_threshold cannot be nil'
      end

      if min_hit_rate_threshold > 100
        fail ArgumentError, 'invalid value for "min_hit_rate_threshold", must be smaller than or equal to 100.'
      end

      if min_hit_rate_threshold < 0
        fail ArgumentError, 'invalid value for "min_hit_rate_threshold", must be greater than or equal to 0.'
      end

      @min_hit_rate_threshold = min_hit_rate_threshold
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] odds_format Object to be assigned
    def odds_format=(odds_format)
      validator = EnumAttributeValidator.new('String', ["american", "decimal", "fractional", "multiplier", "percent"])
      unless validator.valid?(odds_format)
        fail ArgumentError, "invalid value for \"odds_format\", must be one of #{validator.allowable_values}."
      end
      @odds_format = odds_format
    end

    # Custom attribute writer method with validation
    # @param [Object] page Value to be assigned
    def page=(page)
      if page.nil?
        fail ArgumentError, 'page cannot be nil'
      end

      if page < 1
        fail ArgumentError, 'invalid value for "page", must be greater than or equal to 1.'
      end

      @page = page
    end

    # Custom attribute writer method with validation
    # @param [Object] page_size Value to be assigned
    def page_size=(page_size)
      if page_size.nil?
        fail ArgumentError, 'page_size cannot be nil'
      end

      if page_size > 25
        fail ArgumentError, 'invalid value for "page_size", must be smaller than or equal to 25.'
      end

      if page_size < 1
        fail ArgumentError, 'invalid value for "page_size", must be greater than or equal to 1.'
      end

      @page_size = page_size
    end

    # Custom attribute writer method with validation
    # @param [Object] player_id Value to be assigned
    def player_id=(player_id)
      if player_id.nil?
        fail ArgumentError, 'player_id cannot be nil'
      end

      if player_id < 1
        fail ArgumentError, 'invalid value for "player_id", must be greater than or equal to 1.'
      end

      @player_id = player_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] product_mode Object to be assigned
    def product_mode=(product_mode)
      validator = EnumAttributeValidator.new('String', ["sportsbook", "dfs", "prediction_market"])
      unless validator.valid?(product_mode)
        fail ArgumentError, "invalid value for \"product_mode\", must be one of #{validator.allowable_values}."
      end
      @product_mode = product_mode
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] split_type Object to be assigned
    def split_type=(split_type)
      validator = EnumAttributeValidator.new('String', ["overs", "unders"])
      unless validator.valid?(split_type)
        fail ArgumentError, "invalid value for \"split_type\", must be one of #{validator.allowable_values}."
      end
      @split_type = split_type
    end

    # Custom attribute writer method with validation
    # @param [Object] sport_id Value to be assigned
    def sport_id=(sport_id)
      if sport_id.nil?
        fail ArgumentError, 'sport_id cannot be nil'
      end

      if sport_id < 1
        fail ArgumentError, 'invalid value for "sport_id", must be greater than or equal to 1.'
      end

      @sport_id = sport_id
    end

    # Custom attribute writer method with validation
    # @param [Object] team_id Value to be assigned
    def team_id=(team_id)
      if team_id.nil?
        fail ArgumentError, 'team_id cannot be nil'
      end

      if team_id < 1
        fail ArgumentError, 'invalid value for "team_id", must be greater than or equal to 1.'
      end

      @team_id = team_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          bet_type == o.bet_type &&
          betting_market_category_id == o.betting_market_category_id &&
          betting_market_category_ids == o.betting_market_category_ids &&
          betting_market_entity_type == o.betting_market_entity_type &&
          betting_market_ids == o.betting_market_ids &&
          betting_market_position_id == o.betting_market_position_id &&
          betting_market_position_ids == o.betting_market_position_ids &&
          event_id == o.event_id &&
          event_ids == o.event_ids &&
          event_start_date_from == o.event_start_date_from &&
          event_start_date_to == o.event_start_date_to &&
          fact_flow_type == o.fact_flow_type &&
          flow_type == o.flow_type &&
          focus_entity_type_id == o.focus_entity_type_id &&
          full_hit_rate == o.full_hit_rate &&
          include_alt_lines == o.include_alt_lines &&
          include_deeplinks == o.include_deeplinks &&
          include_only_basic_trends == o.include_only_basic_trends &&
          include_star_sign_content == o.include_star_sign_content &&
          league_id == o.league_id &&
          league_ids == o.league_ids &&
          league_key == o.league_key &&
          likelihood_type == o.likelihood_type &&
          max_hit_rate_threshold == o.max_hit_rate_threshold &&
          max_implied_probability_threshold == o.max_implied_probability_threshold &&
          min_hit_rate_threshold == o.min_hit_rate_threshold &&
          min_implied_probability_threshold == o.min_implied_probability_threshold &&
          odds_format == o.odds_format &&
          operator_ids == o.operator_ids &&
          operator_keys == o.operator_keys &&
          page == o.page &&
          page_size == o.page_size &&
          player_id == o.player_id &&
          player_ids == o.player_ids &&
          player_key == o.player_key &&
          product_mode == o.product_mode &&
          split_type == o.split_type &&
          sport_id == o.sport_id &&
          sport_ids == o.sport_ids &&
          sport_key == o.sport_key &&
          starting_soon == o.starting_soon &&
          team_id == o.team_id &&
          team_ids == o.team_ids &&
          team_key == o.team_key &&
          team_split == o.team_split &&
          use_cartoon_images == o.use_cartoon_images
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [bet_type, betting_market_category_id, betting_market_category_ids, betting_market_entity_type, betting_market_ids, betting_market_position_id, betting_market_position_ids, event_id, event_ids, event_start_date_from, event_start_date_to, fact_flow_type, flow_type, focus_entity_type_id, full_hit_rate, include_alt_lines, include_deeplinks, include_only_basic_trends, include_star_sign_content, league_id, league_ids, league_key, likelihood_type, max_hit_rate_threshold, max_implied_probability_threshold, min_hit_rate_threshold, min_implied_probability_threshold, odds_format, operator_ids, operator_keys, page, page_size, player_id, player_ids, player_key, product_mode, split_type, sport_id, sport_ids, sport_key, starting_soon, team_id, team_ids, team_key, team_split, use_cartoon_images].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
